### ISSUE TITLE
Content of the first PR/RFC

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1]
The plan of what will go into the first PR/RFC. Each will likely be a separate commit/patch. Not everything is strictly required, but good to write down anyway.

  - [x] Kbuild
  - [ ] Kconfig
  - [x] Bindings / krustlib / ...
  - [ ] Testing story (e.g. selftests, unit testing, related Kconfig entries, etc.)
  - [ ] Other required changes in infrastructure
  - [ ] First example driver (QEMU/virtio)
  - [ ] Second example driver (ARM/RaspberryPi)

So far discussed in the LPC hackroom with @nickdesaulniers @geofft @joshtriplett @alex @cuviper @arndb Patrick McLean et. al.

**Comment by alex** [comment]
What else do we think needs to be done before this is ready to send upstream?

**Comment by kloenk** [comment]
Vendor dir for building (at least documentation via the KBUILD_CARGOFLAGS).
See #17

**Comment by kloenk** [comment]
We should probably also document what env variables get passed to cargo. I'm thinking of things like CARGO_HOME and CARGO_LOG, as well as RUST_BACKTRACE for build.rs scripts

**Comment by kloenk** [comment]
Also coding style seems missing/not followed

**Comment by ojeda** [comment]
Added Testing to the list as @alex mentioned it the other day.

**Comment by alex** [comment]
@ojeda can kconfig support be checked off now?

**Comment by ojeda** [comment]
@alex I guess, although the two that are ticked still need work (that is why I didn't check them off). In general, there are still many things to do here and there.

**Comment by kloenk** [comment]
> @alex I guess, although the two that are ticked still need work (that is why I didn't check them off). In general, there are still many things to do here and there.

I guess finished kconfig would require resolving of #22?

**Comment by ojeda** [comment]
> I guess finished kconfig would require resolving of #22?

Indeed.

**Comment by ojeda** [comment]
We are using labels to track what is required for the initial upstream, so this is a kind of a duplicate/meta-issue which we don't really use. For discussions around upstreaming etc., we have the ML now.

Thus, closing! :-)
