### ISSUE TITLE
unsuitable for global register variables

### ISSUE THREAD

**Issue by nickdesaulniers** [Rust-for-Linux/linux#100]
today @ojeda mentioned an error with GCC builds ([example](https://github.com/Rust-for-Linux/linux/runs/2047086324?check_suite_focus=true)).

Doing a quick read through llvm's sources, this error diagnostic is called `diag::err_asm_invalid_global_var_reg`, it looks like it can be emitted from `clang::Sema::ActOnVariableDeclarator`  based on `clang::TargetInfo::validateGlobalRegisterVariable`, it looks like there are target specific implementations only for i386 (32b x86).  I can only repro such an error message when building for x86 with `-m32` explicitly set: https://godbolt.org/z/YKcE9v 

Perhaps the incorrect target triple is being passed? For am64, I'd have expected `--target=aarch64-linux-gnu`, but based on the error message, it seems perhaps `--target=i386-linux-gnu` is being used (or some other 32b x86 triple like `i686-linux-gnu`, or an additional flag like `-m32` is being passed).

**Comment by ojeda** [comment]
That's exactly right, the target is missing.

What happened is that https://github.com/torvalds/linux/commit/db07562aeac77923370bff4733d8b0e09cbc93c4 ("Makefile: reuse CC_VERSION_TEXT") conflicted with my `TENTATIVE_CLANG_FLAGS` workaround for GCC builds when merging v5.12-rc2. Then, while resolving it, I didn't notice the condition (which changed) had moved back up where it is in mainline, so we weren't getting the flags at all.

Apologies for the wasted time...

**Comment by ojeda** [comment]
Thanks a lot, that saved me quite some time until I'd have noticed some flags were gone!
