### ISSUE TITLE
rust: sync: add intra-doc links to the `Backend` trait

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1001]
We could use intra-doc links to the `Backend` trait where appropriate, see https://lore.kernel.org/rust-for-linux/94625fe6-b87a-a8f0-5b2a-a8152d5f7436@proton.me/.

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes (generate the docs), to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin, a `Suggested-by:` tag to Benno (see the report above) and a couple `Link:` tags to that report and this issue. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel.

**Comment by Ben2917** [comment]
Hi @ojeda. I'd like to take a look at this

**Comment by ojeda** [comment]
Sure, go ahead, thanks!

**Comment by Ben2917** [comment]
I seem to be having some trouble generating the documentation to test my changes. I've tried running `make LLVM=1 rustdoc` to generate the documentation as described in the docs but I'm getting `no rule to make target 'rustdoc'` as a result. I ran `make help` and see that rustdoc requires "kernel .config" but being a kernel newbie I'm not 100% sure what to do here to enable the rustdoc target. I'm sure I've missed something simple but any help to point me in the right direction would be greatly appreciated!

**Comment by bjorn3** [comment]
Do you have the rust config enabled? Maybe the target doesn't exist if it isn't?

**Comment by ojeda** [comment]
Yes, it requires `RUST=y`.

> I'm sure I've missed something simple but any help to point me in the right direction would be greatly appreciated!

Did you follow the Quick Start guide? https://docs.kernel.org/rust/quick-start.html

**Comment by Ben2917** [comment]
Thanks for your help, I somehow missed the quickstart guide so I was flying a bit blind. I can successfully generate docs now so my patch should be incoming very soon

**Comment by ojeda** [comment]
Glad it helped :) If you hit other roadblocks, we have also a Zulip chat (https://rust-for-linux.com/contact)

**Comment by ojeda** [comment]
Applied to `rust-next`, thanks!
