### ISSUE TITLE
rust: fix sorting of `rust/bindings/bindings_helper.h`'s `#include`s

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1002]
This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes, to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Link:` tag to this issue. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel.

**Comment by wueeh** [comment]
Thank you @ojeda , I'm taking on this

**Comment by ojeda** [comment]
My pleasure! Of course, go ahead :)

**Comment by ojeda** [comment]
Applied 789809a3d540 ("rust: bindings: Order headers alphabetically").
