### ISSUE TITLE
rust: sort `rust/helpers.c`'s `#include`s and add comment about it

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1003]
The comment should be the same as the one found in `rust/bindings/bindings_helper.h`.

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes, to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Suggested-by:` tag and a`Link:` tag to this issue. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel.

**Comment by ariel-miculas** [comment]
I'll take this one.

**Comment by ojeda** [comment]
Thanks -- please go ahead!

**Comment by KimWang906** [comment]
Why is this still open? Isn't this problem solved? Then I would like to contribute to solving this problem.

**Comment by ariel-miculas** [comment]
I have already sent a [patch](https://lore.kernel.org/rust-for-linux/20230426204923.16195-1-amiculas@cisco.com/), not sure if it was merged or not.

**Comment by ojeda** [comment]
I will pick it as soon as the merge window closes.

**Comment by ojeda** [comment]
Applied to `rust-next`, thanks!
