### ISSUE TITLE
Support for the usb subsystem.

### ISSUE THREAD

**Issue by Frostie314159** [Rust-for-Linux/linux#1008]
Is the usb subsystem already available via the kernel crate, since I wasn't able to find anything about it.

**Comment by ojeda** [comment]
No, it is not, though some folks may be interested in it, see e.g. https://github.com/Rust-for-Linux/linux/pull/884 and Zulip topics like https://rust-for-linux.zulipchat.com/#narrow/stream/291566-Library/topic/usb.20subsystem.

(Please post general questions in Zulip, see https://rust-for-linux.com/contact -- thanks!).
