### ISSUE TITLE
Why does so many kernel modules dropped in branch rust-next & rust-dev?

### ISSUE THREAD

**Issue by zhouhaoan** [Rust-for-Linux/linux#1043]
I'm trying to adapt a old rust kernel module project to the latest kernel. However, I found there are a lot of modules dropped in the latest kernel crate. In `rust` branch, there are nearly forty modules but only nine modules are found in branch 'rust-next'.  Are there any articles to introduce the reason? Thanks in advance.

**Comment by bjorn3** [comment]
The rust branch was the old working branch before rust-for-linux was upstreamed. Parts have been upstreamed piece-by-piece as drivers that actually use those bindings get upstreamed. A fair amount of subsystems aren't used by any upstream rust driver yet and as such haven't been upstreamed yet.

**Comment by ojeda** [comment]
Indeed. Please also see https://rust-for-linux.com/branches and related pages.

Also, for general questions, we recommend asking in Zulip instead, please see https://rust-for-linux.com/contact.

Thanks!
