### ISSUE TITLE
Issue of building a minimal kernel with rust support

### ISSUE THREAD

**Issue by ISeekTruth** [Rust-for-Linux/linux#1046]
I want to use the command `make LLVM=1 allnoconfig rust.config` to build a minimal kernel, but I found the rust support flag is not open, how can I do to make it open and support qemu with gdb debug?

**Comment by ojeda** [comment]
Please see https://docs.kernel.org/rust/quick-start.html.

In addition, for questions like this, please use the Zulip chat, not an issue. Please see https://rust-for-linux.com/contact.

Thank you!
