### ISSUE TITLE
Error updating bindgen

### ISSUE THREAD

**Issue by amanuel2** [Rust-for-Linux/linux#1060]
Based on the "rust" branch I get a string of errors. First error I got was exactly [this](https://github.com/Rust-for-Linux/linux/issues/1013) issue, and I applied the patch myself exactly as specified in the lore. 

Now I come onto this error trying to update bindgen after changing it to 0.65.1 as per one of the changes in the lore:

```
> cargo install --locked --version $(scripts/min-tool-version.sh bindgen) bindgen
    Updating crates.io index
warning: no Cargo.lock file published in bindgen v0.65.1
error: there is nothing to install in `bindgen v0.65.1`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency to a Cargo project with `cargo add`.
```

I even tried to hack it around as [per so](https://stackoverflow.com/a/37707083/5768335), but then got the error

```
>  cargo add bindgen                               ✔  1997  00:03:21
error: failed to parse manifest at `/home/aman/Documents/rust-linux/Cargo.toml`

Caused by:
  virtual manifests must be configured with [workspace]
```

Am I missing something entirely here?

**Comment by ojeda** [comment]
Thanks for the report. There are a few things to note:

  - The `rust` branch is archived, please see https://rust-for-linux.com/branches#rust.
  - In mainline Linux we use newer versions of `bindgen`. Mainline or something close to it is generally what you want for Rust development.
  - In newer versions of `bindgen`, `bindgen-cli` is the name of the crate that contains the CLI tool. Please see https://github.com/rust-lang/rust-bindgen/blob/main/CHANGELOG.md#changed-9 and https://docs.kernel.org/next/rust/quick-start.html#bindgen.
  - I am not sure what were you trying to do with `cargo add`, but we do not compile the kernel using Cargo.
