### ISSUE TITLE
Coding Guidelines document renders unordered list inside blockquote

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1063]
The Coding Guidelines document contains an unordered list that, when rendered, is placed inside a `<blockquote>` (which makes it look more indented than expected). Reproduce the issue by building the kernel documentation, fix the document so that the list is not inside a blockquote, and double-check that it is indeed the case in the rendered HTML form.

---

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes (including generating the documentation if changed, running the Rust doctests if changed, etc.), to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Reported-by:` tag and a `Closes:` tag to this issue. Also add a `Fixes` tag. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by VincentWo** [comment]
I would like to "work" on this, I already implemented the change in my local version, should I just send the path to the rust-next mailing list?

**Comment by ojeda** [comment]
Sure, please go ahead! :)

**Comment by ojeda** [comment]
https://lore.kernel.org/rust-for-linux/20240816200339.2495875-1-vincent@woltmann.art/

**Comment by ojeda** [comment]
Applied to `rust-fixes` -- thanks!
