### ISSUE TITLE
Remove unneeded `kernel::prelude::*`s from doctests

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1064]
In the kernel, Rust doctests implicitly include `kernel::prelude::*`. Thus remove it from all doctests from where it may make sense, and double-check they all still compile and pass by running them, e.g. under QEMU or with the KUnit script (see upcoming documentation about how to do so at https://lore.kernel.org/rust-for-linux/20240130075117.4137360-2-dirk.behme@de.bosch.com/).

---

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes (including generating the documentation if changed, running the Rust doctests if changed, etc.), to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Suggested-by:` tag and a `Link:` tag to this issue. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by nellshamrell** [comment]
I would love to work on this issue this week.

**Comment by ojeda** [comment]
Of course, please feel free to -- thanks!

**Comment by nellshamrell** [comment]
# Instances of `kernel::prelude` in doctests

## Tested Examples

- [x] [linux/rust/kernel/net/phys.rs](https://github.com/Rust-for-Linux/linux/blob/9ffe2a730313f27cebd0859ea856247ac59c576c/rust/kernel/net/phy.rs#L769)
- [x] [linux/rust/kernel/workqueue.rs](https://github.com/Rust-for-Linux/linux/blob/768409cff6cc89fe1194da880537a09857b6e4db/rust/macros/lib.rs#L30)

## Untested Examples to possibly re-work
- [x] [linux/rust/kernel/net/phy.rs](https://github.com/Rust-for-Linux/linux/blob/9ffe2a730313f27cebd0859ea856247ac59c576c/rust/kernel/net/phy.rs#L794)
- [ ] [linux/rust/macros/lib.rs](https://github.com/Rust-for-Linux/linux/blob/768409cff6cc89fe1194da880537a09857b6e4db/rust/macros/lib.rs#L30)

Note from zulip on [linux/rust/macros/lib.rs](https://rust-for-linux.zulipchat.com/#narrow/stream/291565-Help/topic/GitHub.20Issue.20.20.231064/near/430171361)

## Other instances

Instances of kernel::{prelude::*, ...} in doctests

- [x] [linux/rust/kernel/init.rs](https://github.com/Rust-for-Linux/linux/blob/768409cff6cc89fe1194da880537a09857b6e4db/rust/kernel/init.rs#L124)

**Comment by nellshamrell** [comment]
A patch for this was submitted to the LKML :)

**Comment by ojeda** [comment]
This is now in mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4a2ae8805129

Thanks again!

**Comment by nellshamrell** [comment]
Amazing! Ty for the opportunity!
