### ISSUE TITLE
Improper rendering of table cell in Arch Support page

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1069]
The [Arch Support](https://docs.kernel.org/rust/arch-support.html) documentation page renders one of the table cells improperly (as an empty bullet list). Please fix it so that the intended rendering (a dash, or similar, meaning "empty/nothing") is used instead.

---

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes (including generating the documentation if changed, running the Rust doctests if changed, etc.), to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Reported-by:` and a `Closes:` tag to this issue. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by BWbwchen** [comment]
Hi, I want to work on this issue.

**Comment by ojeda** [comment]
Of course, please go ahead!

**Comment by BWbwchen** [comment]
Hi @ojeda, 

I have sent the patch. 😃

**Comment by ojeda** [comment]
Thanks!

https://lore.kernel.org/rust-for-linux/20240323074006.2940679-1-tim.chenbw@gmail.com/

**Comment by BWbwchen** [comment]
Hi @ojeda,

I have sent another patch
https://lore.kernel.org/rust-for-linux/20240324010915.3089934-1-tim.chenbw@gmail.com/

Could you help me to review it? Thank you for your help.

**Comment by ojeda** [comment]
The patch looked good overall to me (I didn't try rendering yet, but I assume you tried and it works). We will start taking patches for the cycle soon, no worries. Thanks!

**Comment by BWbwchen** [comment]
Yes, I have rendered it and it worked well.
![Screenshot_20240328_222600](https://github.com/Rust-for-Linux/linux/assets/44916048/cbba2711-79a5-40c5-8da4-d53c36104d0c)

**Comment by ojeda** [comment]
Fixed in commit 01848eee20c6 ("docs: rust: fix improper rendering in Arch Support page").
