### ISSUE TITLE
How do I compile a Linux kernel for the aarch64 platform

### ISSUE THREAD

**Issue by Haker0428** [Rust-for-Linux/linux#1071]
I want to build a bin file to raspberrypi4b or rk chip, and develop some driver. In rust-dev branch, I saw that the arch-support.rst document says that aarch64 is supported, and how can I compile a Linux kernel for the aarch64 platform.

**Comment by ojeda** [comment]
Please ask general questions in Zulip (https://rust-for-linux.com/contact) -- this issue tracker is not meant for that.
