### ISSUE TITLE
Example on Character Devices?

### ISSUE THREAD

**Issue by brummer-simon** [Rust-for-Linux/linux#1072]
Hi Rust-for-Linux Team,

Nearly a year ago, I was curious trying out linux kernel development on rust, I found an example implementing a character device in this repository, I tweaked it a little bit and in the end, I was happy with the results. Today wanted to update my experimental setup, I've updated to the latest commit on 'rust-next' and all traces of the Rust wrappers, I've have previously used, were gone. I also noticed that branch 'rust' that I've used back then is stale by now. So my questions are:

1) Out of curiosity: What happened back then?
2) Are character devices still supported?
3) In case the answer to "2" was yes: Is there an example that shows how to implement a simple character device working against 'rust-next' or some other current branch?

Thanks for your awesome work!
     Cheer Simon

**Comment by ojeda** [comment]
We are now in mainline and the kernel requires a user for abstractions (and code in general) to be upstreamed -- if you have one in mind, then it would be very interesting to hear about it. Please see https://rust-for-linux.com/branches and https://rust-for-linux.com/contributing as well as other pages in the website -- they contain a lot of useful information/context to get started.

> Thanks for your awesome work!

Our pleasure! If you don't mind, could you please ask this in Zulip (https://rust-for-linux.com/contact) instead?

**Comment by brummer-simon** [comment]
> We are now in mainline and the kernel requires a user for abstractions (and code in general) to be upstreamed -- if you have one in mind, then it would be very interesting to hear about it. Please see https://rust-for-linux.com/branches and https://rust-for-linux.com/contributing as well as other pages in the website -- they contain a lot of useful information/context to get started.

I would love to have an Idea to bring the integration forward but I choose character devices for my experimentation because they are easy. I am pretty sure that is not enough to move it forward.

> > Thanks for your awesome work!
> 
> Our pleasure! If you don't mind, could you please ask this in Zulip (https://rust-for-linux.com/contact) instead?

Won't do. I have seen that somebody asked the same question a few weeks ago.
