### ISSUE TITLE
Move proc-macro documentation into the `kernel` crate

### ISSUE THREAD

**Issue by BennoLossin** [Rust-for-Linux/linux#1076]
Currently all examples in the `macros` crate are `ignore`d, since they are depending on stuff from the `kernel` crate. There are several reasons for why we would like them to not be ignored:
- It shows up in the documentation as "This example is not tested" and might confuse readers.
- We should execute those examples as tests.
- It helps keep them up-to date, since are need to compile.

A solution is to move the documentation from the `macros` crate into the `kernel` crate via using [re-exports](https://doc.rust-lang.org/stable/rustdoc/write-documentation/re-exports.html). When doing this, please also ensure that the tests compile.

---
This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes, to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and so on. Please see https://docs.kernel.org/process/submitting-patches.html and https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by bjorn3** [comment]
It should be possible to build the macro crate as rmeta, then build the kernel crate as rmeta and finally rustdoc the macro crate with the kernel crate as dependency, right? It just needs both version of the macro crate to be compiled with different `-Cmetadata` arguments.

**Comment by BennoLossin** [comment]
> It should be possible to build the macro crate as rmeta, then build the kernel crate as rmeta and finally rustdoc the macro crate with the kernel crate as dependency, right? It just needs both version of the macro crate to be compiled with different `-Cmetadata` arguments.

Hmm I have no idea if that works, but if anyone wants to try it, feel free to do so.

**Comment by AmateurECE** [comment]
I plan on submitting a patch series for this either tonight or tomorrow. The approach I took to enable these tests is mostly similar to what @bjorn3 suggested above, only I haven't found so far that explicit distinct `-Cmetadata` arguments are required. I'll be looking for some feedback to sanity check my approach 🙂.

**Comment by bjorn3** [comment]
> only I haven't found so far that explicit distinct -Cmetadata arguments are required.

Surprising. I did still recommend using a distinct `-Cmetadata` argument just in case not passing it currently works due to a bug. If this bug were to be fixed in the future and you aren't passing `-Cmetadata` it would break.

**Comment by ojeda** [comment]
With Ethan's series (landing in v6.13), this can be closed:

ae7851c29747 ("rust: macros: enable the rest of the tests")
7e06561fcd96 ("rust: macros: enable paste! use from macro_rules!")
8d3f50795ac2 ("rust: enable macros::module! tests")
b2c261fa8629 ("rust: kbuild: expand rusttest target for macros")
