### ISSUE TITLE
make `InPlaceInit` compatible with `Arc`

### ISSUE THREAD

**Issue by BennoLossin** [Rust-for-Linux/linux#1079]
Currently `InPlaceInit` is not implemented for `Arc`, because `pin_init()` returns a `Pin<Self>`. But `Arc` implicitly pins its contents, so the return type should actually be just `Self`.

Add an associated type to `InPlaceInit` that is then used as the return type. Also implement `InPlaceInit` for `Arc` and `ListArc` if available [^1].

---
This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes, to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and so on. Please see https://docs.kernel.org/process/submitting-patches.html and https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

[^1]: Note that currently only [v1](https://lore.kernel.org/rust-for-linux/20240402-linked-list-v1-1-b1c59ba7ae3b@google.com/) of the list abstractions exist, so `ListArc` might not be upstreamed.

**Comment by ellcs** [comment]
Hi! I am new to the kernel development, and this looks doable to me. So I work on this.

**Comment by wqld** [comment]
Hi @ellcs, are you working on this? If you are busy, would be it okay if I do it?

**Comment by ellcs** [comment]
> Hi @ellcs, are you working on this? If you are busy, would be it okay if I do it?

Hi @wq, i have the patch ready to submit. I want to read some more kernel documentation before submitting it. I will submit it in the next days :)

**Comment by ojeda** [comment]
https://lore.kernel.org/rust-for-linux/20240717034801.262343-2-alexmantel93@mailbox.org/

**Comment by ojeda** [comment]
Applied to `rust-next`. Thanks!
