### ISSUE TITLE
Writing an linux kernel module in Rust

### ISSUE THREAD

**Issue by lwz23** [Rust-for-Linux/linux#1083]
Hi, I am currently learning to write linux kernel modules in rust. Are there any suitable modules waiting to be rewritten in Rust? And is there already a good use case for rewriting linux kernel modules in Rust?

**Comment by ojeda** [comment]
Welcome!

Please see https://rust-for-linux.com/contributing -- we have some ideas there. I would also recommend joining our Zulip (https://rust-for-linux.com/contact) and asking there -- the issue tracker is not meant for general questions. Thanks!
