### ISSUE TITLE
Help - rust kernel module development 

### ISSUE THREAD

**Issue by alloc33** [Rust-for-Linux/linux#1093]
I'd like to learn how to build linux kernel modules using Rust. My main question - which kernel should I use? I have macmini with latest Asahi linux (Fedora) server running. Even tho I installed Asahi using official guide - it's kernel didn't have proper Rust support so I cloned the repo intself and installed this kernel manually

`grep -i 'RUST' .config` (Asahi linux repo):
<img width="487" alt="Screenshot 2024-07-31 at 6 20 50 PM" src="https://github.com/user-attachments/assets/365963af-f335-44c0-a9e7-6c37d061e7a3">

`grep -i 'RUST' .config` (This repo):
<img width="459" alt="Screenshot 2024-07-31 at 6 21 22 PM" src="https://github.com/user-attachments/assets/6968f08f-89e0-4610-94ef-4925053dc3ba">

Why does this repo have "less rust in config"?

**Comment by ojeda** [comment]
Generally kernel development is done in mainline, unless you don't care about upstreaming your code or you have specific requirements like using Rust abstractions that are not yet upstream.

But please ask these questions in our Zulip, this issue tracking is meant for actual issues -- see https://rust-for-linux.com/contact. Thanks!
