### ISSUE TITLE
Quick Start document renders unordered list inside blockquote

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1103]
The Quick Start document contains an unordered list that, when rendered, is placed inside a `<blockquote>` (which makes it look more indented than expected). Reproduce the issue by building the kernel documentation, fix the document so that the list is not inside a blockquote, and double-check that it is indeed the case in the rendered HTML form.

---

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes (including generating the documentation if changed, running the Rust doctests if changed, etc.), to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Reported-by:` tag and a `Closes:` tag to this issue. Also add a `Fixes` tag. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by mulderje** [comment]
I would like to give this issue a go. If it is still available I'll give it a go over the next few days. Thanks for doing these "good first issue" tags to help better understand the submission process.

**Comment by ojeda** [comment]
Sure, please go ahead!

> Thanks for doing these "good first issue" tags to help better understand the submission process.

You're welcome, I hope they are useful (it does take some time to manage them, so thanks for mentioning that :)

**Comment by mulderje** [comment]
Just sent out the patch using b4 as a test. Looks like I double-dipped on the cover letter/patch notes. Is there anything I should be doing different there or does that just happen when there is only one patch in the series? 

https://lore.kernel.org/rust-for-linux/20240826-pr-docs-rust-remove-quickstart-blockquote-v1-1-c51317d8d71a@gmail.com/T/#u

**Comment by ojeda** [comment]
For single patches, most likely you don't need a cover letter. For series with more than one patch, typically one is needed (but it is not a hard rule -- the goal is to be as clear as possible, so it depends on what you are doing). Thanks for the patch!

**Comment by ojeda** [comment]
Applied to `rust-fixes` and going to Linus soon -- thanks!
