### ISSUE TITLE
Clean `kernel::block::mq::Request` docs to render properly

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1108]
There are several documentation rendering issues in `rust/kernel/block/mq/request.rs`. For instance, there is an ordered list not rendering as such in -- clean it up so that it is rendered properly. There is also some inline code missing Markdown quotes nearby -- clean it up too. There are also some references to types that could be intra-doc links and/or are missing Markdown quotes.

---

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes (including generating the documentation if changed, running the Rust doctests if changed, etc.), to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Suggested-by:` tag and a `Link:` tag to this issue. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by frazar** [comment]
Hi! Thanks for the very clear write-up. I would like to work on this issue.

**Comment by ojeda** [comment]
You're welcome -- please go ahead!
