### ISSUE TITLE
Move unfit code out of `rust/kernel/types.rs`

### ISSUE THREAD

**Issue by BennoLossin** [Rust-for-Linux/linux#1117]
`rust/kernel/types.rs` is a rather non-descriptive, general file that contains code that might be better suited somewhere else:
-  `ARef<T>` and `AlwaysRefCounted` should be in `rust/kernel/sync/aref.rs`. 
- `FromBytes` and `AsBytes` traits and implementations should be in `rust/kernel/transmute.rs`.

Please create two separate patches for the above. Also take care to fix any imports and rustdoc examples.

---
This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes (including generating the documentation if changed, running the Rust doctests if changed, etc.), to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Suggested-by: tag` and a `Link:` tag to this issue. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by nbdd0121** [comment]
I feel like `convert` doesn't coney the semantics of these traits are only performing byte-level transmutation. Maybe `transmute.rs`?

**Comment by plinkr** [comment]
Hey! I would like to give this issue a try if no one is working on it

**Comment by plinkr** [comment]
I sent the patches: https://lore.kernel.org/rust-for-linux/20240918225115.2309224-1-aliet.exposito@gmail.com/T/#t
Thank you very much for the opportunity to work on a `good first issue`

**Comment by sergiocollado** [comment]
The patch looks good ....  but `transmute.rs` for me it feels a bit too eldritch and arcane ....  `convert` or `convertBytes` or something similar sounded better, at least for me.  Otherwise looks great!

**Comment by ojeda** [comment]
@sergiocollado I assume it is following `std::mem::transmute`.

Applied to `rust-next` -- thanks everyone!
