### ISSUE TITLE
Make Error use NonZero for its value

### ISSUE THREAD

**Issue by Darksonn** [Rust-for-Linux/linux#1120]
Currently, the type `Result<(), Error>` takes up twice the size that it needs to. By changing the type inside `Error` to be the appropriate `NonZero*` type will make the niche optimization apply to reduce the size.

Related to https://github.com/Rust-for-Linux/linux/issues/195.

**Comment by felipeagger** [comment]
I will work on it.

**Comment by ojeda** [comment]
https://lore.kernel.org/rust-for-linux/CANiq72kMg=HKkuTTUhGDmCamgJ1c1JSM8HZyUKwA9yi_6nF3iQ@mail.gmail.com/
