### ISSUE TITLE
Clean all the Clippy warnings in `drivers/gpu/drm/drm_panic_qr.rs`

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1123]
Clean all the Clippy warnings in `drivers/gpu/drm/drm_panic_qr.rs`.

The DRM maintainers will need to be involved, since the patch will go through them. For some warnings, there may be different ways of solving it, so it may require figuring out the best way for each for them.

---

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes (including generating the documentation if changed, running the Rust doctests if changed, etc.), to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Reported-by: tag` and a `Closes:` tag to this issue. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by GuilhermeGiacomoSimoes** [comment]
I don't is specialist in clippy ... But , how I can run the clippy on the linux kernel without Cargo.toml ? 
Can I isolate the rust code in another directory and create the Cargo.toml and run Clippy ?

**Comment by tgross35** [comment]
All the Rust tools work without Cargo - `clippy_driver` is a direct drop in for `rustc`. Just build with `CLIPPY=1` :)

**Comment by Witcher01** [comment]
I'm relatively new to kernel development so I'll leave this here if anyone is stumbling a little as well: Don't forget to enable `DRM_PANIC_SCREEN_QR_CODE` in `.config` so the relevant code compiled in the first place and build with `make LLVM=1 CLIPPY=1` drivers/gpu/drm/`.

@GuilhermeGiacomoSimoes Do you want to work on this? If not, I'd like to implement this and make my first contribution to the kernel!

**Comment by GuilhermeGiacomoSimoes** [comment]
Okay @Witcher01 , you can make resolve this issue. 
I take another issue.

**Comment by Witcher01** [comment]
I just sent the patches. Here's the thread: https://lore.kernel.org/rust-for-linux/20241012075312.16342-1-witcher@wiredspace.de/T/#t

Thanks for your help Miguel :)

**Comment by ojeda** [comment]
You're welcome! :)

Let's see what the author and DRM maintainers say.

Nicely written series, by the way.

**Comment by kdj0c** [comment]
@Witcher01 Thanks for this series.

If you want to test the QR code, without building the whole kernel, I've copied the rust code to a small project here: https://gitlab.com/kdj0c/qr_panic/

src/main.rs is almost identical to drm_panic_qr.rs, and you can test it with "cargo run", it's much easier to iterate, and see the result.
I will try to keep qr_panic up to date with the kernel.

**Comment by Witcher01** [comment]
> Nicely written series, by the way.

Thank you! @ojeda 

> If you want to test the QR code, without building the whole kernel, I've copied the rust code to a small project here: https://gitlab.com/kdj0c/qr_panic/

Thanks @kdj0c I'll keep it in mind!

I'm currently quite short on time and energy to work on things outside of my dayjob, but I'll prepare a new series in the coming days with all the suggestions applied. Thanks to everyone for the feedback!

**Comment by ojeda** [comment]
> but I'll prepare a new series in the coming days with all the suggestions applied.

Just to confirm, is v2 the result? That was a couple hours! :) I can apply it already on `rust-next` in that case.

Thanks!

**Comment by Witcher01** [comment]
On Sat Oct 19, 2024 at 12:52 PM CEST, Miguel Ojeda wrote:
> Just to confirm, is v2 the result? That was a couple hours! :) I can
> apply it already on `rust-next` in that case.

Yes, sorry for the confusion. It turned out I had enough time today
after all, so I rewrote the patch quickly! Please feel free to include
it in rust-next if v2 is good as it is, I'm not planning any other
things if the reviewers deem it acceptable. :)

Thanks again for the opportunity and the feedback, I hope my schedule
will allow for some more free time again soon so I can tackle bigger
things regarding Rust for Linux and do what I can to help!

**Comment by ojeda** [comment]
> Yes, sorry for the confusion. It turned out I had enough time today
> after all, so I rewrote the patch quickly! Please feel free to include
> it in rust-next if v2 is good as it is, I'm not planning any other
> things if the reviewers deem it acceptable. :)

Great, applied -- thanks! :)

(I noticed we missed a `Closes`, so GitHub closed this due to that commit getting pushed -- I corrected it).

> Thanks again for the opportunity and the feedback, I hope my schedule
> will allow for some more free time again soon so I can tackle bigger
> things regarding Rust for Linux and do what I can to help!

That would be great!
