### ISSUE TITLE
Impl `fmt::Display` for kernel `Box<T, A>`

### ISSUE THREAD

**Issue by fbq** [Rust-for-Linux/linux#1126]
Currently `fmt::Display` is not implemented for `Box<T, A>`, due to we have our own allocator implementation. The following code should just work if we have `impl fmt::Display` for that:

```rust
let v = KBox::new(42, GFP_KERNEL)?;
println!("{}", v);
```
---

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes (including generating the documentation if changed, running the Rust doctests if changed, etc.), to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and to add a `Suggested-by: tag` and a `Link:` tag to this issue. Please see https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by JCKeep** [comment]
I am new to the Kernel development and I would like to take it if is possible.

**Comment by ojeda** [comment]
Sure, please go ahead!

**Comment by ojeda** [comment]
https://lore.kernel.org/rust-for-linux/tencent_2AD25C6A6898D3A598CBA54BB6AF59BB900A@qq.com/

**Comment by JCKeep** [comment]
Thanks @ojeda. 👍

**Comment by ojeda** [comment]
Thanks to you for doing the work! :)

Closing speculatively, since it is in `rust-next` now, so unless something extraordinary happens, it will be eventually merged into mainline in a few weeks.
