### ISSUE TITLE
MAINTAINERS entry - small correction?

### ISSUE THREAD

**Issue by jabedude** [Rust-for-Linux/linux#123]
Hi all, looks like this entry in MAINTAINERS references a non-existent file: https://github.com/Rust-for-Linux/linux/blob/967a297234f69957a0f267566bfffd6ae2558087/MAINTAINERS#L15558

Should this instead be:
```
F:	drivers/char/rust_example.rs
```

**Comment by ojeda** [comment]
Yeah, it should. I didn't get around to update the entry (that file will also move somewhere else very soon, too :-)

Thanks for reporting! I thought nobody read those ;-)
