### ISSUE TITLE
rust example register called twice. why?

### ISSUE THREAD

**Issue by omac777** [Rust-for-Linux/linux#127]
It's not issue, but a question.
https://github.com/Rust-for-Linux/linux/blob/rust/drivers/char/rust_example.rs#L140

```
        let mut chrdev_reg =
            chrdev::Registration::new_pinned(cstr!("rust_chrdev"), 0, &THIS_MODULE)?;
        chrdev_reg.as_mut().register::<RustFile>()?;
        chrdev_reg.as_mut().register::<RustFile>()?;
```
Why is register called twice?

Thank you

**Comment by alex** [comment]
Because the goal is to demo what it looks like to register multiple chardevs on the same major number. We're being lazy and just using the same file type.

Would a comment explaining this help?

**Comment by omac777** [comment]
yes it would help because the intention is not explicitly clear.
Thank you for clarifying.  It makes sense.

    On Friday, March 19, 2021, 5:11:51 p.m. EDT, Alex Gaynor ***@***.***> wrote:  
 
 


Because the goal is to demo what it looks like to register multiple chardevs on the same major number. We're being lazy and just using the same file type.

Would a comment explaining this help?
