### ISSUE TITLE
Provide a general `PointerWrapper`

### ISSUE THREAD

**Issue by fbq** [Rust-for-Linux/linux#144]
There are situations that we want to use `PointerWrapper` outside `file_operatoins` modules. We should make it to a more public place like `kernel::types'.

**Comment by Sylfrena** [comment]
Hi, can I work on this issue?

**Comment by fbq** [comment]
> Hi, can I work on this issue?

Sure, feel free to ask any question. Please do let me when you send a PR, thanks!

**Comment by Sylfrena** [comment]
@fbq  PTAL
