### ISSUE TITLE
Pre-RFC review: two tiny spell-fixes

### ISSUE THREAD

**Issue by jabedude** [Rust-for-Linux/linux#149]
s/iff/if/ in rust/kernel/sync/mutex.rx+spinlock.rs:

https://github.com/Rust-for-Linux/linux/blob/98898dfbdf722e64b6c092d16d217b8e88a01347/rust/kernel/sync/spinlock.rs#L55
https://github.com/Rust-for-Linux/linux/blob/98898dfbdf722e64b6c092d16d217b8e88a01347/rust/kernel/sync/mutex.rs#L41

**Comment by ojeda** [comment]
"iff" here means "if and only if".

I agree that spelling it fully would be better, since otherwise one always doubts whether it was an (unfortunate) typo.

**Comment by ojeda** [comment]
Thanks a lot for the pre-RFC review, by the way!

**Comment by jabedude** [comment]
> I agree that spelling it fully would be better, since otherwise one always doubts whether it was an (unfortunate) typo.

Ah, I had no idea! No worries, my mistake 😄
