### ISSUE TITLE
Custom `alloc`

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#199]
We will most likely need to customize `alloc` to ensure fallible allocations everywhere, as well as being able to pass flags etc.

**Comment by ojeda** [comment]
From @Ericson2314 in #204:

> i have opened https://github.com/rust-lang/wg-allocators/issues/87 and https://github.com/rust-lang/rust/pull/84266 about this. Should be easy to pass the appropriate flags to rustc to disable that feature if the PR or something like it lands.

**Comment by Ericson2314** [comment]
https://github.com/rust-lang/rust/pull/84266 is now merged. The raw CFG is hard to use from Cargo but should be fine for us. This will remove all the problematic functionality at compile time.
