### ISSUE TITLE
Dropping `chrdev`/`miscdev::Registration` and similar

### ISSUE THREAD

**Issue by adamrk** [Rust-for-Linux/linux#233]
The current setup of `chrdev` and `miscdev` will lead to UAF if the returned `Registration` is dropped, but there's nothing that prevents the device driver from doing that. It's pretty clear from the examples, but it'd just be a shame if someone trying this out for the first time writes a very simple driver in totally `safe` Rust and gets a UAF error because they miss this point.

I also introduced a new type like this in https://github.com/Rust-for-Linux/linux/pull/232 so if we end up with a bunch then maybe there should at least be some documentation/warnings about them? Not sure if we can do anything better than.

**Comment by wedsonaf** [comment]
How can one trigger this UAF?

**Comment by adamrk** [comment]
Ah, you're right. I was just forgetting to de-register in the `Drop` when following a similar pattern. Sorry for the confusion.
