### ISSUE TITLE
`rustdoc 1.51.0-nightly` does not work

### ISSUE THREAD

**Issue by kloenk** [Rust-for-Linux/linux#238]
When running `make O=build rustdoc`, rustdoc fails with the error `error: too many file operands`.

As far as I can see it, this is, as `rustdoc` does not support the `@file` cmd argument. I also found no documentation of this feature for rustdoc, which let's me wonder how it ever worked. Should we create an issue at the rust repo, asking for support for that flag?

**Comment by bjorn3** [comment]
This was implemented in https://github.com/rust-lang/rust/pull/82261 will be included in rustc 1.52.0.

**Comment by kloenk** [comment]
Ok. will leave this open, until rust 1.52.0 is merged in nixpkgs. installing newer rustdoc would be not that easy for me.

**Comment by kloenk** [comment]
There is now an open pr onto staging for rustc 1.52.0.
https://github.com/NixOS/nixpkgs/pull/122110
