### ISSUE TITLE
Prepare to change target logic

### ISSUE THREAD

**Issue by alex** [Rust-for-Linux/linux#25]
If  https://github.com/rust-lang/rust/pull/77916 lands in upstream rust, we'll need to change the target we compile with. The new target makes more sense anyways :-)

**Comment by ojeda** [comment]
Yeah, although this shows why rustc should not need to have the target to begin with. Unless there is a reason not to, it is cleaner to have it on our end. That eliminates a dependency on a common name, resolves the "naming dispute" FIXME and avoids rustc having to track all possible targets out there. It seems like they [might agree](https://github.com/rust-lang/rust/issues/74247#issuecomment-706777438), so I supported that view in https://github.com/rust-lang/rust/issues/74247

**Comment by Ericson2314** [comment]
I'm in now way official over there, to be clear, but yes you state my view exactly! I don't think these sorts of layer violations help anyone.

**Comment by ojeda** [comment]
In #28 I go the route of having our own target spec.

**Comment by alex** [comment]
@ojeda was this obsoleted by the switch to not use cargo?

**Comment by ojeda** [comment]
It was obsoleted by #28 given we use custom targets, although I didn't close this given the discussions are ongoing e.g. see the overview I wrote yesterday at https://github.com/rust-lang/rust/issues/71009. But changing the title or closing this and creating a new issue makes sense.

**Comment by alex** [comment]
I'm going to close this, given the precise original reason I filed it for has been obviated.
