### ISSUE TITLE
Speed up CI with ccache

### ISSUE THREAD

**Issue by alex** [Rust-for-Linux/linux#262]
Right now our CI spends a lot of time recompiling C code for the kernel that rarely changes. We should be able to leverage ccache (or something similar) to get better CI performance. This would improve the experience for developers.

https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/ is an example of what setting this up might look like.

**Comment by bjorn3** [comment]
sccache also supports rust. It may not support all used rustc arguments though.
