### ISSUE TITLE
Is there and documentation about the building process of Rust code in Kernel?

### ISSUE THREAD

**Issue by d0u9** [Rust-for-Linux/linux#271]
Aside from the API and ABI, building system is very import as well. As a quick glimpse  of this [POST], it doesn't mention anything about how to build this sample module in/out kernel source tree.

So, is there any clue about this topic?

[POST]: https://security.googleblog.com/2021/04/rust-in-linux-kernel.html

**Comment by TheSven73** [comment]
Hi from Toronto ! Take a look at [this link](https://github.com/Rust-for-Linux/linux/blob/rust/Documentation/rust/quick-start.rst). Hope it's useful :)

**Comment by ojeda** [comment]
Closing since it was answered (also, please use the mailing list for general questions/help).
