### ISSUE TITLE
Consider opting for `unsafe_op_in_unsafe_fn`

### ISSUE THREAD

**Issue by nbdd0121** [Rust-for-Linux/linux#285]
`#![warn(unsafe_op_in_unsafe_fn)]` will no longer make `unsafe fn` imply a `unsafe {}` surrounding the body. We should consider switching it on to make all unsafe operations explicit, even inside `unsafe fn`. This will ensure that all operations in `unsafe fn` still have their invariants audited and upheld.

This feature is stablised in Rust 1.52 so we may want a newer version of Rust nightly.

**Comment by ojeda** [comment]
I would definitely want that.

**Comment by ojeda** [comment]
Depends on #135.
