### ISSUE TITLE
Current use of `pin` is unsound

### ISSUE THREAD

**Issue by nbdd0121** [Rust-for-Linux/linux#286]
In rust_miscdev, this would compile:
```rust
let mut state = SharedState::try_new()?;
let mut state2 = SharedState::try_new()?;
core::mem::swap(Arc::get_mut(&mut state).unwrap(), Arc::get_mut(&mut state2).unwrap()); 
```

but this swaps two pinned `CondVar`, which is unsound. After pinning the `CondVar`, we shouldn't be able to obtain any `Arc<SharedState>`, but rather only `Pin<Arc<SharedState>>`.

**Comment by alex** [comment]
The right fix here is:

a) To pin the `Arc` immediately here: https://github.com/Rust-for-Linux/linux/blob/rust/samples/rust/rust_miscdev.rs#L42
b) To change teh return type to `Pin<Arc<SharedState>>` here: https://github.com/Rust-for-Linux/linux/blob/rust/samples/rust/rust_miscdev.rs#L41
c) To update anything else to get it to compile :-)
