### ISSUE TITLE
Warnings when running `rustdoc` on `rust/kernel/traits.rs`

### ISSUE THREAD

**Issue by wedsonaf** [Rust-for-Linux/linux#307]
I'm getting the following warnings when running `make rustdoc`.

This is also visible on CI ([example here](https://github.com/Rust-for-Linux/linux/pull/305/checks?check_run_id=2689142892)), so it's not a configuration issue on my side

```
warning: unresolved link to `Box`
  --> rust/kernel/traits.rs:11:68
   |
11 | /// Common pointer types which implement a `pin()` method include [`Box`], [`Arc`] and [`Rc`].
   |                                                                    ^^^^^ no item named `Box` in scope
   |
   = note: `#[warn(broken_intra_doc_links)]` on by default
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Rc`
  --> rust/kernel/traits.rs:11:89
   |
11 | /// Common pointer types which implement a `pin()` method include [`Box`], [`Arc`] and [`Rc`].
   |                                                                                         ^^^^ no item named `Rc` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: 2 warnings emitted
```

@TheSven73 it looks like this was introduced by 02138fd952a65ab8b72ce55de59587de6b2b14af.

**Comment by TheSven73** [comment]
I'll fix. Should we let the CI error out on rustdoc warnings?

**Comment by wedsonaf** [comment]
> I'll fix.

Thanks!

> Should we let the CI error out on rustdoc warnings?

I think we should, in fact I was surprised to find out that we don't.

**Comment by TheSven73** [comment]
> I think we should, in fact I was surprised to find out that we don't.

Same. The CI succeeded, so I didn't even look at rustdoc's output.
I'll add rustdoc err-on-warn to the fix PR.

**Comment by TheSven73** [comment]
Hm. There are plenty of other rustdoc warnings, not only coming from `traits.rs`. The amount and types of warnings appear to change depending on the platform being built.

**Comment by ojeda** [comment]
> I think we should, in fact I was surprised to find out that we don't.

IIRC, I did not enable it right away because we did not have yet docs for all public bits etc. But yes, we definitely want to enable it.
