### ISSUE TITLE
Pull request cannot pass Github's CI.

### ISSUE THREAD

**Issue by d0u9** [Rust-for-Linux/linux#331]
I recently made a small change to the Makefile, and issued a pull request.

I noticed that some CI cases was cancelled due to either downloading timeout or passive cancellation, and then this pull request is marked as "Some checks were not successful".

I wonder
1) what can I do when stuck in such a situation;
2) These failures seem not due to code flaws, what can I do to avoid this.

**Comment by ojeda** [comment]
GitHub's CI is indeed quite flaky. In a handful of months, we have seen downtime, issues with apt mirrors, stuck runners, intermittent failures on artifact uploads, etc. It is free though, so we cannot complain too much :)

For you: do not worry about it too much -- simply ask us in a comment to re-run it. If you have already checked your code in your fork, it should not happen too many times.

If Rust in the kernel is successful and everyone ends up using it, then the long-term solution will be having our own self-hosted runners sponsored by some of the LF companies etc. :)

**Comment by ojeda** [comment]
Closing -- for general questions that are not related to code etc., please use the mailing list or the Zulip chat.

**Comment by ojeda** [comment]
By the way, I will make @ksquirrel take commands soon -- I may make the "re-run checks" one the first one ;)

**Comment by d0u9** [comment]
It sounds great, automation is always important. :)
