### ISSUE TITLE
Add GitHub problem matchers

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#332]
Ideally for all the following:
  - `rustc`, Clippy and `rustdoc` warnings/errors etc.
  - The kernel log (from QEMU): `BUG :`, `WARNING: `, oops/panics, etc.

e.g. like for GCC/Clang here:
  - https://github.com/linuxppc/linux-ci/blob/merge/.github/problem-matchers/gcc.json
  - https://github.com/ClangBuiltLinux/continuous-integration2/blob/main/.github/problem-matchers/clang-errors-warnings.json

How it looks in action (see "Annotations"): https://github.com/linuxppc/linux-ci/actions/runs/774767088

For more info see:
  - https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md
  - https://github.com/ClangBuiltLinux/continuous-integration2/issues/122

**Comment by bjorn3** [comment]
actions-rs/cargo has the following problem matcher: https://github.com/actions-rs/cargo/blob/master/.matchers/rust.json

**Comment by sergiocollado** [comment]
Maybe this could be a starting point: #729

**Comment by sergiocollado** [comment]
#768
