### ISSUE TITLE
rust: linked_list: add examples

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#345]
Add usage examples to `rust/kernel/linked_list.rs`'s `List`.

**Comment by ojeda** [comment]
Pinging @wedsonaf in case he wants to comment (e.g. it may be too early to add usage examples if he wants to change the module, since it is a work in progress).

**Comment by wedsonaf** [comment]
I'm working on the `rbtree` submodule now and we may need to change the linked list for consistency. There are constraints in `rbtree` that we didn't have with lists but that dictate certain aspects of the solution. For example, links (prev/next) point to links themselves or the outer object? Here we had a choice, but we don't in `rbtree` as we're using the kernel implementation.

**Comment by devillove084** [comment]
@wedsonaf Is the linked list still inconsistent with the red-black tree to a certain extent as you said? Need to continue to improve? Is it necessary to use the kernel to implement a linked list? I hope to contribute to the community from this issue. Thank you very much.

**Comment by RoKu1** [comment]
Is this still open to take ??

**Comment by ojeda** [comment]
> Is this still open to take ??

José submitted a PR as shown above (#937).

**Comment by ojeda** [comment]
Closing, since it does not apply anymore (it was from the out-of-tree days) -- though more examples in the upcoming doubly-linked list in mainline (currently in `rust-next`) would not hurt! :)
