### ISSUE TITLE
Check whether `bindgen` can generate callbacks without `unsafe`

### ISSUE THREAD

**Issue by wedsonaf** [Rust-for-Linux/linux#43]
For example, in file_operations we are forced to declare the functions as unsafe. It would be better if we could minimise the amount of unsafe code within the function by annotating just the unsafe operations.

**Comment by kloenk** [comment]
IIRC everything which has extern C has to be unsafe, as it's out of the control of rustc. ld links it in, which is after rustc

**Comment by ojeda** [comment]
> IIRC everything which has extern C has to be unsafe, as it's out of the control of rustc. ld links it in, which is after rustc

You're probably thinking about calling external C functions, but here we are defining functions in Rust to be called by C, which may be safe. For instance, this works:

    pub extern fn f() {}

**Comment by ojeda** [comment]
Closing -- nowadays we build with `-Dunsafe_op_in_unsafe_fn` (and it will be warn-by-default in Rust 2024): https://github.com/Rust-for-Linux/linux/issues/285.
