### ISSUE TITLE
alloc_error_handler feature no longer necessary

### ISSUE THREAD

**Issue by bjorn3** [Rust-for-Linux/linux#431]
It's use was removed in https://github.com/Rust-for-Linux/linux/pull/426.

https://github.com/Rust-for-Linux/linux/blob/4d68cd74ff20adba73151d2c29da6a6050106b05/rust/kernel/lib.rs#L17

**Comment by bjorn3** [comment]
I also can't easily find a use of `concat_idents`.

**Comment by wedsonaf** [comment]
> I also can't easily find a use of `concat_idents`.

It's used in binder: https://github.com/Rust-for-Linux/linux/blob/4d68cd74ff20adba73151d2c29da6a6050106b05/drivers/android/defs.rs#L12

**Comment by bjorn3** [comment]
I see. It should be possible to implement `concat_idents!` with a proc_macro to avoid this unstable feature. (Choose the span of either inputs and then call `Ident::new` with this span and the concatenated ident name.)

**Comment by ojeda** [comment]
Thanks for catching that @bjorn3.

> I also can't easily find a use of `concat_idents`.

For the features, I keep track of them in #2 (with where they are used).
