### ISSUE TITLE
I can't find Rust Support even if HAS_RUST is enabled and COMPILE_TEST is disabled

### ISSUE THREAD

**Issue by Typedefining** [Rust-for-Linux/linux#440]
I use Ubuntu 20.04. And I'm sure I installed rustc, rustup.
So, I want to know where can I write something like : RUST_SUPPORT=y?

**Comment by Typedefining** [comment]
I disable MODVERSIONS, and it works.

**Comment by SocialistDalao** [comment]
Same problem with the same situation. And it is fixed with the same solution of disabling MODVERSIONS first.

**Comment by ojeda** [comment]
`MODVERSIONS` support is coming; `COMPILE_TEST` should also go away when we go into mainline.

**Comment by SocialistDalao** [comment]
WoW Great to hear that!
