### ISSUE TITLE
Data structures that cannot be moved (e.g., self-referential ones) should be properly tagged with Pin

### ISSUE THREAD

**Issue by wedsonaf** [Rust-for-Linux/linux#46]
This gives a clear indication to the user of the data structure that they cannot be safely moved.

**Comment by alex** [comment]
What's the remaining scope for this now that we did chrdev?

**Comment by alex** [comment]
Per our call this weekend, I'm going to go ahead and close this. If we discover mroe places we ought to be using `Pin`, we can give them their own issues.
