### ISSUE TITLE
[QUESTION] Divide x86 and amd64?

### ISSUE THREAD

**Issue by ghost** [Rust-for-Linux/linux#460]
As we are talking about Linux kernel, I's like ti suggest to divide the generally speaking x86 in x86 (for 32bit) and amd64 (for 64bit), this makes easier to check for progress (for eh: under arches it's not really useful to check for x86 and the see "x86_64 only". What do you think? Could this be a good point? Is/are there any thing/s against that?

**Comment by ojeda** [comment]
We are following the `arch/` names, as well as the same as the LLVM doc too.

In any case, x86 32-bit support should be coming soon (I took a look yesterday, but there is something I need to debug).
