### ISSUE TITLE
`pr_` macros evaluate arguments in `unsafe` blocks

### ISSUE THREAD

**Issue by wedsonaf** [Rust-for-Linux/linux#479]
So something like:

```rs
let x = &10u32 as *const u32;
pr_info!("{}", *x);
```

compiles when it should require an explicit `unsafe` block around `*x`.

This is actually a recurring problem we've been finding with our macros. Is there anything we can do to detect this automatically?

**Comment by nbdd0121** [comment]
It would be fixed by #300

**Comment by ojeda** [comment]
Submitted fix at: https://lore.kernel.org/rust-for-linux/20230109204912.539790-1-ojeda@kernel.org/

**Comment by ojeda** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6618d69aa129a8fc613e64775d5019524c6f231b.
