### ISSUE TITLE
Should we add a `Mutex::new_and_init()` function?

### ISSUE THREAD

**Issue by d0u9** [Rust-for-Linux/linux#494]
Currently, to use `Mutex<T>`, the user has to 1. new a mutex; 2. call `init()` on it.

For most cases, the user always hope to own an initialized mutex instead of one which is not ready for work.

So, why don't we have a function like `new_and_init()` for Mutex? What is the concern?

**Comment by bjorn3** [comment]
The problem is that you aren't allowed to move the mutex after calling `.init()`. Returning a 
a mutex necessarily moves it, so it isn't allowed to return a mutex after initializing it.

**Comment by d0u9** [comment]
Is that due to the `Pin<>` wrapper?

**Comment by bjorn3** [comment]
Kind of. The `Pin` wrapper is used to enforce the non-movability. It is the mutex implementation of Linux itself that adds this constraint. It can create self-referential mutexes in some cases.

**Comment by d0u9** [comment]
I guess what you are talking about is the internal link in the implementation of mutex itself? After initialization, the mutex struct is inserted into this link, and cannot be moved any longer.

Can this constrain be overcome by something like:

```rust
struct Mutex<T> {
    inner: Pin<MutexInner<T>>,
}
```

**Comment by d0u9** [comment]
I guess what you are talking about is the internal link list in the implementation of mutex itself? After initialization, the mutex struct is inserted into this link, and cannot be moved any longer.

Can this constrain be overcome by something like:

```rust
struct Mutex<T> {
    inner: Pin<MutexInner<T>>,
}
```

The `MutexInner` itself remains in a fix location in memory, and we can safely move its wrapper around. Not sure, please correct me.

**Comment by bjorn3** [comment]
No, `Pin<T>` doesn't make `T` immovable. In fact moving the `Pin<T>` moves the `T`. It makes the value `T` dereferences to immovable. This means `Pin` must always contain some kind of pointer. Either a mutable reference or a heap allocated value. Eg `Pin<&mut T>`, `Pin<Box<T>>` or `Pin<Rc<T>>`. `Pin<&mut T>` won't work in most cases mutex is used as where do you store the value behind the reference? `Pin<Box<T>>` would work, but requires a costly heap allocation and as such isn't an option either.

**Comment by d0u9** [comment]
> `Pin<Box<T>>` would work, but requires a costly heap allocation and as such isn't an option either.

I think what you intend to say is:

```rust
struct Mutex<T> {
    inner: Pin<Box<MutexInner<T>>,
}

struct MutexInner<T> {
    mutex: UnsafeCell<bindings::mutex>,
    _pin: PhantomPinned,
    data: UnsafeCell<T>,
}
```

Does the "**requires a costly heap allocation**" statement say that `Box<>` induces double memory allocation? One for the `MutexInner<T>` on the head, and another for the data wrapping this mutex.
