### ISSUE TITLE
Pahole

### ISSUE THREAD

**Issue by chadbrewbaker** [Rust-for-Linux/linux#515]
Pahole is in a separate repo. https://git.kernel.org/pub/scm/devel/pahole/pahole.git/

It is a utility for shrinking struct layouts https://lwn.net/Articles/335942/

Could we add it as a repo? Not only so the infrastructure is in place for more kernel test tooling, but also because the lack of pahole support is something Rust needs.  Eventually pahole features should probably be upstreamed to Rust mainline and llvm mainline.

**Comment by alex** [comment]
I don't understand what the request is here.

I'm not sure this is required for Rust in any event -- rustc automatically orders struct fields to minimize wasted padding bytes.

**Comment by ojeda** [comment]
Yes, please clarify the request.
