### ISSUE TITLE
TLA+

### ISSUE THREAD

**Issue by chadbrewbaker** [Rust-for-Linux/linux#516]
This project should fork the Linux TLA+ specs. https://git.kernel.org/pub/scm/linux/kernel/git/cmarinas/kernel-tla.git/

TLA+ is a formal specification tool.  https://lamport.azurewebsites.net/tla/learning.html 

It should be routine to add a spec anytime we add Rust code that has distributed/async effects. 

On one end of the spectrum Sel4 has specs down into assembler https://github.com/seL4/l4v/blob/master/spec/cspec/X64/Kernel_C.thy  on the other end AWS has added property tests into their Rust code https://assets.amazon.science/07/6c/81bfc2c243249a8b8b65cc2135e4/using-lightweight-formal-methods-to-validate-a-key-value-storage-node-in-amazon-s3.pdf  and they also use a TLA+ alternative https://github.com/p-org/p .

**Comment by ojeda** [comment]
I would be delighted to see more specs, but this is out of scope at the moment.
