### ISSUE TITLE
Make chardev use Pin<T> the way miscdev does

### ISSUE THREAD

**Issue by alex** [Rust-for-Linux/linux#53]

**Comment by ojeda** [comment]
Related: #46

**Comment by alex** [comment]
Ok, starting to sketch out a design here: Is it important that chrdev be able to support arbitrary (runtime) controlled number of registrations, or is it fine to be controlled at compile time?

If it's fine to have fixed number per registration only then the design is much simpler :-)

**Comment by ojeda** [comment]
Many drivers are fine with a fixed number. We can always put the compile-time one for the moment, then think about making it more flexible later.
