### ISSUE TITLE
Add a method to CStr to get `&str` out of it

### ISSUE THREAD

**Issue by foxhlchen** [Rust-for-Linux/linux#532]
Currently, when you want to print the content of a `CStr`, you need to first call `.as_bytes()` and pass it to `core::str::from_utf8` to get `&str` then use it in pr_*! macros, It's quite inconvenient.

We can add a helper method to `CStr` to get `&str` out of it.

As discussed by @wedsonaf in Zulip, appropriate naming is important, some namings are not good:

`as_str` implies it's free which is not true.

`to_str` isn't suitable because it's fallible

implementing `TryFrom/TryInto` or/and `as_str_unchecked` (`core::str::from_utf8_unchecked`) may be a good one.

**Comment by bjorn3** [comment]
`std::ffi::CStr` has a method `fn to_str(&self) -> Result<&str, Utf8Error>`.

**Comment by ojeda** [comment]
> then use it in pr_*! macros, It's quite inconvenient.

Could we implement `Display` for `CStr`/`BStr`? (in addition to these methods, which are useful)

**Comment by bjorn3** [comment]
Yes, but you will have to replace non-utf-8 bytes when passing it to the formatter.

**Comment by ojeda** [comment]
+1, we should avoid panicking if we find invalid UTF-8.
