### ISSUE TITLE
Upload kernel image to GitHub

### ISSUE THREAD

**Issue by kloenk** [Rust-for-Linux/linux#54]
We could store the bzImage on GitHub, and just download from there to make testing easier: https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts

**Comment by ojeda** [comment]
Trying this out, it seems uploading artifacts is unreliable: it failed for me twice in separate runs. It also makes the jobs fail, so for the moment, let's just avoid it -- we don't need it that much anyway.

See e.g. https://github.com/actions/upload-artifact/issues/71
