### ISSUE TITLE
Create proper type for `File`'s flags

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#606]
From @wedsonaf https://github.com/Rust-for-Linux/linux/pull/603#issuecomment-1004880436:

> One aspect of this PR that I'm not completely happy with is that we're returning a `u32` without any mention of the meaning. So users need to read to the Rust code to figure out that it refers to `f_flags`, then the C code to figure out what those refer to, then they'll be forced to use constants in `bindings` to check specific flags.
>
> So in addition to the winding path to find the actual flags, there is the problem that they are in a module that we intend to eventually make private.
>
> For cases like this I've taken two different approaches, depending on whether the values can be ORed (which is the case here):
> 1. If the values are unique, I declare an enum (e.g., [`ExtraResult`](https://github.com/Rust-for-Linux/linux/blob/4f082c4a01a3e275ee5a44836d5c7d63c62ad2d5/rust/kernel/irq.rs#L81))
> 2. If they can be ORed, I declare a type and publish the constants in it (e.g., [`Type`](https://github.com/Rust-for-Linux/linux/blob/4f082c4a01a3e275ee5a44836d5c7d63c62ad2d5/rust/kernel/irq.rs#L276)), then mention it in the documentation of the method (e.g., [`set_type`](https://github.com/Rust-for-Linux/linux/blob/4f082c4a01a3e275ee5a44836d5c7d63c62ad2d5/rust/kernel/irq.rs#L117)).
>
> Ideally we'd do something similar here.

**Comment by danobi** [comment]
I can take this. I'll see if I can find any time this week/weekend

**Comment by felixfaisal** [comment]
Can i take this on, Or probably shadow @danobi ?
