### ISSUE TITLE
Mark functions generated by the module! macro as unsafe

### ISSUE THREAD

**Issue by bjorn3** [Rust-for-Linux/linux#629]
Most of them are unsafe despite not being marked as such. For example `fn __init` and `fn __exit` contain unsynchronized accesses to `static mut __MOD`. There are also several `extern "C"` functions which call `__init` and `__exit`. These need to be marked as unsafe too.

cc https://rust-for-linux.zulipchat.com/#narrow/stream/288089-General/topic/patch.20v3.20review/near/268298086

**Comment by crapStone** [comment]
If this issue is still available I'd like to give it a try

**Comment by bjorn3** [comment]
It is. Feel free to give it a try.

**Comment by Darksonn** [comment]
This was fixed by [this patch](https://lore.kernel.org/all/20240401185222.12015-1-benno.lossin@proton.me/) which went in via `rust-fixes-6.9`.
