### ISSUE TITLE
It is recommended not to put rust in the kernel root directory

### ISSUE THREAD

**Issue by dukelec** [Rust-for-Linux/linux#631]
It seems very incongruous, it is recommended to create a directory dedicated to support other languages, and you can continue to add other languages c++, xust, yust, zust... in the future.

It is also recommended that rust not be enabled by default in the future.

This way, users who do not want to use rust can ignore it.

Please don't try to force people to learn and use rust, as it will only make people feel more resentful.

**Comment by daviessm** [comment]
By whom is it recommended?
