### ISSUE TITLE
Support riscv

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#66]
This architecture is becoming more popular as time passes and is on the forefront of open research, so it would be a fitting and welcome addition to provide its users with Rust support. In particular, the 64-bit one.

Linux riscv targets with official Ubuntu binutils etc. support:

    Linux arch  QEMU target      LLVM target  Ubuntu binutils             Example Rust triple
    ----------  ---------------  -----------  --------------------------  -------------------

    riscv       riscv64-softmmu  RISCV        binutils-riscv64-linux-gnu  riscv64gc-unknown-none-elf

In particular, there is no official 32-bit Ubuntu binutils package so far.

**Comment by HKalbasi** [comment]
Anything remaining for this?

**Comment by ojeda** [comment]
RISC-V is supported upstream nowadays.
