### ISSUE TITLE
I didn't find "Rust support" in "General setup"

### ISSUE THREAD

**Issue by tivrfoa** [Rust-for-Linux/linux#690]
Hi!

I'm following: https://github.com/Rust-for-Linux/linux/blob/rust/Documentation/rust/quick-start.rst

```sh
make LLVM=1 rustavailable
***
*** Rust compiler 'rustc' is too new. This may or may not work.
***   Your version:     1.61.0
***   Expected version: 1.59.0
***
***
*** Rust bindings generator 'bindgen' is too new. This may or may not work.
***   Your version:     0.59.2
***   Expected version: 0.56.0
***
Rust is available!
```

Then I run `make menuconfig` and I didn't find Rust there.

**Comment by ojeda** [comment]
Could you please search (`/`) for `RUST` inside `menuconfig` and post what it reports in the `Depends on` line?

Note that `CONFIG_RUST` depends on `CONFIG_RUST_IS_AVAILABLE`, but also other bits (that will be reduced over time as much as possible).

In addition, the `menuconfig` etc. should be done with `LLVM=1` too if you intend to compile with LLVM.

Finally, if it is the first time you are trying it, please use the expected versions of the toolchain!

**Comment by tivrfoa** [comment]
```
 Symbol: RUST [=n]
  │ Type  : bool
  │ Defined at init/Kconfig:2056
  │   Prompt: Rust support
  │   Depends on: RUST_IS_AVAILABLE [=y] && (ARM64 || CPU_32v6 || CPU_32v6K || PPC64 && CPU_LITTLE_ENDIAN || X86_64 [=y] || RISCV) && !MODVERSIONS [=y] && !GCC_PLUGIN_RANDSTRUCT [=n]
  │   Location:
  │     Main menu
  │ (1)   -> General setup
  │ Selects: CONSTRUCTORS [=n]
```

Running with LLVM=1 (`make LLMV=1 menuconfig`) I got:
```
scripts/Kconfig.include:40: linker 'ld.lld' not found
make[1]: *** [scripts/kconfig/Makefile:48: menuconfig] Error 1
make: *** [Makefile:667: menuconfig] Error 2
```

I'm searching how to solve this now =)

**Comment by ojeda** [comment]
So this is the culprit:

    !MODVERSIONS [=y]

If you disable `MODVERSIONS`, you should see the `Rust support` entry, since all the other dependencies are met.

**Comment by ojeda** [comment]
As for the linker not found error, you will need to install LLD if you want to use `LLVM=1`. Please see Documentation/kbuild/llvm.rst.

**Comment by tivrfoa** [comment]
> As for the linker not found error, you will need to install LLD if you want to use `LLVM=1`. Please see Documentation/kbuild/llvm.rst.

Running with `make LD=/usr/bin/ld.lld-11 LLVM=1 menuconfig` it worked!

Now I'll try to compile it.
Thank you very much!

**Comment by ojeda** [comment]
I am glad it helped! :)

**Comment by tivrfoa** [comment]
> Finally, if it is the first time you are trying it, please use the expected versions of the toolchain!

Yes, I think I'll need to do that:

```rust
***
*** Rust compiler 'rustc' is too new. This may or may not work.
***   Your version:     1.61.0
***   Expected version: 1.59.0
***
***
*** Rust bindings generator 'bindgen' is too new. This may or may not work.
***   Your version:     0.59.2
***   Expected version: 0.56.0
***
  RUSTC L rust/core.o
  BINDGEN rust/bindings_generated.rs
  BINDGEN rust/bindings_helpers_generated.rs
error[E0501]: cannot borrow `self.iter` as mutable because previous closure requires unique access
   --> /home/lesco/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:182:9
    |
182 | /         self.iter
183 | |             .try_fold(init, |acc, x| match Try::branch(x) {
    | |              --------       -------- closure construction occurs here
    | |              |
    | |              first borrow later used by call
184 | |                 ControlFlow::Continue(x) => ControlFlow::from_try(f(acc, x)),
185 | |                 ControlFlow::Break(r) => {
186 | |                     *self.residual = Some(r);
    | |                     -------------- first borrow occurs due to use of `self` in closure
187 | |                     ControlFlow::Break(try { acc })
188 | |                 }
189 | |             })
    | |______________^ second borrow occurs here

error[E0500]: closure requires unique access to `self` but it is already borrowed
   --> /home/lesco/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:183:29
    |
182 | /         self.iter
183 | |             .try_fold(init, |acc, x| match Try::branch(x) {
    | |              --------       ^^^^^^^^ closure construction occurs here
    | |              |
    | |              first borrow later used by call
184 | |                 ControlFlow::Continue(x) => ControlFlow::from_try(f(acc, x)),
185 | |                 ControlFlow::Break(r) => {
186 | |                     *self.residual = Some(r);
    | |                     -------------- second borrow occurs due to use of `self` in closure
187 | |                     ControlFlow::Break(try { acc })
188 | |                 }
189 | |             })
    | |______________- borrow occurs here

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0500, E0501.
For more information about an error, try `rustc --explain E0500`.
make[1]: *** [rust/Makefile:368: rust/core.o] Error 1
make: *** [Makefile:1267: prepare] Error 2
```

**Comment by bjorn3** [comment]
Libcore should now be compiled with the 2021 edition. It is currently built for the 2018 edition: https://github.com/Rust-for-Linux/linux/blob/6e0fac63e663d94860463bebb887ab8c5446b96d/rust/Makefile#L366

**Comment by tivrfoa** [comment]
> Libcore should now be compiled with the 2021 edition. It is currently built for the 2018 edition:
> 
> https://github.com/Rust-for-Linux/linux/blob/6e0fac63e663d94860463bebb887ab8c5446b96d/rust/Makefile#L366

I changed to 2021 and got lots of errors.
rust 1.61.0
bindgen 0.59.2

I'll try with the correct versions.
[rust-errors-2021.txt](https://github.com/Rust-for-Linux/linux/files/8165385/rust-errors-2021.txt)

**Comment by ojeda** [comment]
> Libcore should now be compiled with the 2021 edition. It is currently built for the 2018 edition:

Not in 1.59.0, which is the current supported version (of course, you are right that soon we will need to change that bit):

https://github.com/rust-lang/rust/blob/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/Cargo.toml#L9

@tivrfoa: the issue is that you are trying to compile with a too-new version, as the script reports. It is possible to fix, but it is not supported (and we do not really want to try to support several Rust versions at the moment). That is why you should use the proper version, unless you want to fix things on your side (which usually involves more changes than just an edition, e.g. `alloc` changes, possibly removed features, etc.).

**Comment by tivrfoa** [comment]
It worked with the correct versions: rustc (1.59.0), bindgen (0.56.0) and edition 2018.

`make` didn't finish yet, but it passed the Rust phase.

Can someone share a minimum '.config' to compile with Rust, please? =)

**Comment by ojeda** [comment]
Please take a look in the `.github/workflows/` folder. For general questions and help, please open a thread in Zulip.
