### ISSUE TITLE
Document installation of Rust development files

### ISSUE THREAD

**Issue by YakoYakoYokuYoku** [Rust-for-Linux/linux#695]
After building the kernel at version 5.16.12 (testing purposes only), I've tried to compile a test module based on the `rust-out-of-tree` template.
This has obviously failed because the required development files weren't under `/usr/src/linux`.
Then I've put `arch/x86/rust/target.json` plus `rust` into the appropiate places under the headers path but I've stumbled upon another issue, this time I've got a target mismatch in the lines of

```stdout
$ make KDIR=/usr/src/linux LLVM=1
make -C /usr/src/linux M=$PWD
make[1]: Entering directory '/usr/lib/modules/5.16.12-arch1-1/build'
  RUSTC [M] /home/yakoyoku/Codes/Rust/Tests/kernelmoduletest/printk/rust_printk.o
error[E0461]: couldn't find crate `core` with expected target triple target-11037152212728156790
  |
  = note: the following crate versions were found:
          crate `core`, target triple target-289699297990821728: /usr/lib/modules/5.16.12-arch1-1/build/rust/libcore.rmeta

error: aborting due to previous error

make[2]: *** [scripts/Makefile.build:364: /home/yakoyoku/Codes/Rust/Tests/kernelmoduletest/printk/rust_printk.o] Error 1
make[1]: *** [Makefile:1986: /home/yakoyoku/Codes/Rust/Tests/kernelmoduletest/printk] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.16.12-arch1-1/build'
make: *** [Makefile:4: default] Error 2
```

But building with `make KDIR=~/Codes/ArchPackages/linux/repos/core-x86_64/src/archlinux-linux LLVM=1`, i.e. the location of the build directory of the `linux` package, does work.

Where I'm going to is that it would be very useful to have documentation for the files required Rust hacking or to keep this issue for future reference otherwise.

**Comment by ojeda** [comment]
> Where I'm going to is that it would be very useful to have documentation for the files required Rust hacking or to keep this issue for future reference otherwise.

I am not sure I understand -- the `README.md` in https://github.com/Rust-for-Linux/rust-out-of-tree-module explains the need to have a kernel with Rust enabled and includes an example with `KDIR` showing how it should be compiled.

**Comment by YakoYakoYokuYoku** [comment]
To better contextualize I'm wanting to address what does the `rust-out-of-tree` `README.md` says

> The kernel tree (`KDIR`) requires the Rust metadata to be available. These are generated during the kernel build, but may not be available for installed/distributed kernels (the scripts that install/distribute kernel headers etc. for the different package systems and Linux distributions are not updated to take into account Rust support yet).

If I use the system development files (`/usr/src/linux`) I get the target triple hash error but if I use the build directory it doesn't get a hash mismatch. At the moment I'm thinking that this is due to missing files but I don't know.

Edit: typo

**Comment by ojeda** [comment]
> if I use the build directory it does get a hash mismatch.

In the first message you said it worked when you used the correct `KDIR`. Could you please clarify?

Also, a couple general comments on this:

> Then I've put `arch/x86/rust/target.json` plus `rust` into the appropiate places under the headers path
>
> (...) the files required Rust hacking

The Rust support here is meant to be used as provided, with the intention of upstreaming it. You should not need to copy any files etc. Instead, please use the repository as provided. Backporting to other versions is (of course) possible but we do not support that.

**Comment by YakoYakoYokuYoku** [comment]
> Backporting to other versions is (of course) possible but we do not support that.

Yeah and I've stumbled upon the problem of module loading, i.e. `amdgpu` or `dm-mod` (perhaps this is somewhat related to #495 and it could be mentioned in #663).

> The Rust support here is meant to be used as provided, with the intention of upstreaming it. You should not need to copy any files etc. Instead, please use the repository as provided.

Kinda a bummer that building with the development files outside the repository is not yet supported nonetheless I hope this could be doable in the future.

**Comment by bjorn3** [comment]
Part of rust-for-linux (the rust standard library and the kernel crate) need to be compiled directly into the kernel the way it is setup currently. While it would likely be possible to change this to include them as part of the kernel module, this would grow the kernel module quite a bit and probably wouldn't allow different drivers written in rust to exist both as part of kernel and in a kernel module due to symbol conflicts.

**Comment by ojeda** [comment]
> Kinda a bummer that building with the development files outside the repository is not yet supported nonetheless I hope this could be doable in the future.

Please note it is not in the plan to support that. As @bjorn3 mentions, like for C, the idea is to have some common support built-in inside the kernel, and then have modules use it; instead of having each module bring every abstraction/dependency with them.

**Comment by ojeda** [comment]
> Yeah and I've stumbled upon the problem of module loading, i.e. `amdgpu` or `dm-mod` (perhaps this is somewhat related to https://github.com/Rust-for-Linux/linux/issues/495 and it could be mentioned in https://github.com/Rust-for-Linux/linux/issues/663).

Could you please open a new issue with details?

**Comment by YakoYakoYokuYoku** [comment]
Post-it: The rmeta files contain a field that describe their target, i.e. if it's a JSON file the absolute will be there, but those cannot be monkey patched because it doesn't give you the same hash.

> Could you please open a new issue with details?

At the moment I have the issue sorted, turns out that the BTF stripping in a debug build (`CONFIG_DEBUG_INFO_BTF` and `CONFIG_PAHOLE_HAS_SPLIT_BTF`) was not working well with branch 5.16, I suspect that either `pahole` or `resolve_btfids` was the culprit. Otherwise, I can boot in Qemu with the options disabled.

**Comment by ojeda** [comment]
Thanks for the details! I am not sure why you want to modify the target that way, but it should not be required/needed.

**Comment by YakoYakoYokuYoku** [comment]
I was testing if modifying the `.rmeta` files like that could at least give me a hash that matches with the one of `make KDIR=/lib/modules/$(uname -r)/build` but I didn't got lucky.
