### ISSUE TITLE
Makefile: a grep regular expression in the rust/Makefile may have problem

### ISSUE THREAD

**Issue by Richardhongyu** [Rust-for-Linux/linux#696]
https://github.com/Rust-for-Linux/linux/blob/28a9bd2ebd821ab0f412f1d661c62801dbd2f632/rust/Makefile#L273-L274
When I learn the process of rust-bindgen, I find this expression confusing to me. Does the second part of this regular expression have a redundant "$"? If the answer is a yes, should I open a pr for it? Thanks for your advice!

**Comment by Richardhongyu** [comment]
I figure it out. Makefile uses $$ to represent $ in the shell.

**Comment by ojeda** [comment]
For future questions, please use Zulip.

**Comment by Richardhongyu** [comment]
I wrongly thought this was a bug. I will use Zulip to assure whether this is a bug first next time.

**Comment by ojeda** [comment]
No worries -- and thanks for reviewing the code. :)
