### ISSUE TITLE
Synchronize volunteer

### ISSUE THREAD

**Issue by stappersg** [Rust-for-Linux/linux#70]
Hi,

Visiting this report shows a scary

>  This branch is 71 commits ahead, 14138 commits behind torvalds:master. 

I'm voluntering to reduce the   amounts of _commits behind torvalds_

Please grant me the privilege to push to this git repository.

**Comment by alex** [comment]
We resync with master after releases, we're currently built off of 5.10. I think this is a quirk of how github computes these stats, and not really meaningful in any sense.

If you're interested in contributing, you're always welcome to send pull requests.
