### ISSUE TITLE
I'm unable to reach any codes in `bcm_2835_rng_rust.rs` at runtime.

### ISSUE THREAD

**Issue by SocialistDalao** [Rust-for-Linux/linux#704]
These days, I'm trying to run rust4linux in `qemu-system-aarch64` to figure out how rust drivers work. I choose `bcm_2835_rng_rust` as it is simpler than the GPIO rust driver. However, I'm unable to reach any codes of it at runtime. BCM2835 emulation configuration guide in qemu is quite hard to find. 

I know that `rust_random.rs` has made a software rng sample. But what I really care about is the implementation of rust codes interacting with **real devices**. Could you tell me how can I achieve this goal? I also think this might be an important part in the future documentation.

Thank you.

**Comment by ojeda** [comment]
Rust drivers use the same interfaces to userspace as the C ones. Please see https://github.com/Rust-for-Linux/linux/pull/254 for more code and a very nice guide on how to run it in QEMU or in real hardware that @TheSven73 wrote.

(Also, for general questions, please ask in Zulip).

**Comment by SocialistDalao** [comment]
NICE Guide!!! I'll take a look at this. 

By the way, it seems that only invited persons can ask questions in Zulip. Could you please invite me?

Email: loancold@foxmail.com

**Comment by ojeda** [comment]
Of course, invitation sent!
