### ISSUE TITLE
Have documented that we are at 5.10

### ISSUE THREAD

**Issue by stappersg** [Rust-for-Linux/linux#71]
This issue is for telling  that there is no reason get scared upon seeing

>  This branch is 71 commits ahead, 14138 commits behind torvalds:master. 

We, this repository, already are at  version 5.10 of Linux,  see also #70.

When we are at  v5.11 we should have an open issue that tells so. It is for telling busy people that project is in very healthy state.

**Comment by ojeda** [comment]
The kernel does receive a lot of thousands of commits every couple of months or so, it is common to be behind that much since development is typically based on earlier tags rather than arbitrary points from `master`.

What do you mean by "have an open issue"?

**Comment by stappersg** [comment]
> What do you mean by "have an open issue"?

Having a communication channel, providing additional information.
A way to share incrowd knowledge with new project members.

**Comment by ojeda** [comment]
Do you mean like a pinned issue? I don't think issues should be used like that. Ascertaining whether a project is healthy or not is typically done by checking out the dates of the latest commits, the list of issues, PRs, etc.; and all of those have very recent activity.

**Comment by stappersg** [comment]
Yes a _pinned issue_ can provide the information that makes first time visitors into returning visitors.

Speaking for myself:   I think this project is in early experimental  stage.  And experiments are good,  I have several going on.   I can't afford more.


Possible content for the _pinned issue_:

We are on par with released versions of Linux kernel.  So when you have a recent kernel, you are close to `sudo insmod foo` where `foo` is the module you have written in Rust.  We recommend to verify your build environment by
`make -C path/to  bar`. `bar` is our known good demo kernel module.
Meanwhile we continue to get our effort upstream.

**Comment by ojeda** [comment]
Please note that, at the moment, this project is meant for kernel and Rust developers, not end users. If we were supporting users, then it could be a good idea to have a pinned issue with the most common problems that users may face etc.

In any case, the information needed (by developers) to get started is in the front page (from the `README.md` file).
