### ISSUE TITLE
modpost: "build_error" undefined

### ISSUE THREAD

**Issue by SocialistDalao** [Rust-for-Linux/linux#755]
When I enable `GPIO_PL061_RUST` and build this module, it shows error:

`ERROR: modpost: "build_error" [drivers/gpio/gpio_pl061_rust.ko] undefined!`

I found that functions like `IoMem::readl()` will call `IoMem::check_offset()`, which then calls `build_assert!()` and finally reaches `build_assert!()` and `build_error()`. How can I fix this?

**Comment by bjorn3** [comment]
Do you have optimizations enabled? If not I think you need to disable the RUST_BUILD_ASSERT_DENY config.

**Comment by SocialistDalao** [comment]
- `RUST_OPT_LEVEL_SIMILAR_AS_CHOSEN_FOR_C` and `RUST_BUILD_ASSERT_WARN`:

 ```shell
  ld.lld: warning: rust/built-in.a(build_error.o):(.gnu.warning.build_error) is being placed in '.gnu.warning.build_error'
  
  ERROR: modpost: "build_error" [drivers/gpio/gpio_pl061_rust.ko] undefined!
 ```

- `RUST_OPT_LEVEL_0` and `RUST_BUILD_ASSERT_WARN` : SAME.

- `RUST_OPT_LEVEL_0` and `RUST_BUILD_ASSERT_ALLOW` : No warning but still modpost undefined.

**Comment by SocialistDalao** [comment]
`RUST_OPT_LEVEL_3` and `RUST_BUILD_ASSERT_DENY`: PASS

`RUST_OPT_LEVEL_3` and `RUST_BUILD_ASSERT_WARN`: PASS with warning

``` ld.lld: warning: rust/built-in.a(build_error.o):(.gnu.warning.build_error) is being placed in '.gnu.warning.build_error'```

Maybe the `IoMem` bounds check can't be guaranteed at compile time. If I open the optimization option, `build_error` will be optimized to `panic!()` and gives me warnings. This means the program may contain bugs?
