### ISSUE TITLE
Negative module refcount number together with `rmmod` error

### ISSUE THREAD

**Issue by zhouhaoan** [Rust-for-Linux/linux#781]
**Description**

I build two modules in samples/rust. After I installed it, it shows a negative refcount number. When I tried to remove it, `rmmod` raise an error.
   Here are my steps:
   1. make menuconfig
   2. make LLVM=1
   3. make modules_install
   4. make install
   5. reboot
   6. sudo insmod /lib/modules/.../rust_xxx.ko
   7. lsmod  (**Negative refcount occured here**)
   8. sudo rmmod rust_xxx.ko   
   >rmmod: ERROR: Module unloading is not supported

   
![截图 2022-05-31 23-47-28](https://user-images.githubusercontent.com/55027252/171217768-2c48756d-370e-486e-8aba-85626f084d11.png)

**Architecture(s)**
  x86_64 , Intel , real machine

**Toolchain versions**
  - `rustc`: 1.59.0
  - `bindgen`: 0.56.0
  - LLVM/Clang: 14.0.0
  - GCC: 10.3.0
  - QEMU: not a virtual machine
  - Linux kernel: v5.17-rc6

<details><summary><strong>Kernel log</strong></summary>
<p>

```text
...
[   71.573617] evbug: Event. Dev: input10, Type: 1, Code: 96, Value: 1
[   71.573620] evbug: Event. Dev: input10, Type: 0, Code: 0, Value: 0
[   71.603553] rust_print: Rust printing macros sample (init)
[   71.603556] rust_print: Emergency message (level 0) without args
[   71.603558] rust_print: Alert message (level 1) without args
[   71.603559] rust_print: Critical message (level 2) without args
[   71.603559] rust_print: Error message (level 3) without args
[   71.603560] rust_print: Warning message (level 4) without args
[   71.603560] rust_print: Notice message (level 5) without args
[   71.603560] rust_print: Info message (level 6) without args
[   71.603561] rust_print: A line that is continued without args
[   71.603562] rust_print: Emergency message (level 0) with args
[   71.603563] rust_print: Alert message (level 1) with args
[   71.603564] rust_print: Critical message (level 2) with args
[   71.603564] rust_print: Error message (level 3) with args
[   71.603565] rust_print: Warning message (level 4) with args
[   71.603565] rust_print: Notice message (level 5) with args
[   71.603565] rust_print: Info message (level 6) with args
[   71.603566] rust_print: A line that is continued with args
[   71.653614] evbug: Event. Dev: input10, Type: 4, Code: 4, Value: 458840
[   71.653625] evbug: Event. Dev: input10, Type: 1, Code: 96, Value: 0
...
[  110.883623] evbug: Event. Dev: input10, Type: 1, Code: 28, Value: 1
[  110.883627] evbug: Event. Dev: input10, Type: 0, Code: 0, Value: 0
[  110.894131] rust_semaphore: Rust semaphore sample (init)
[  110.953635] evbug: Event. Dev: input10, Type: 4, Code: 4, Value: 458792
[  110.953647] evbug: Event. Dev: input10, Type: 1, Code: 28, Value: 0
...
(Can't find module exit info)

```

</p>
</details>

<details><summary><strong>Kernel config</strong></summary>
<p>

```text
...
CONFIG_SAMPLES=y
...
CONFIG_SAMPLES_RUST=y
...
CONFIG_SAMPLE_RUST_PRINT=m
...
CONFIG_SAMPLE_RUST_SEMAPHORE=m
...
```

</p>
</details>

**Comment by nbdd0121** [comment]
-2 is `-ENOENT`, meaning that you did not have `CONFIG_MODULE_UNLOAD` enabled.

**Comment by zhouhaoan** [comment]
> -2 is `-ENOENT`, meaning that you did not have `CONFIG_MODULE_UNLOAD` enabled.

Thanks a lot. I have solve the problem.
