### ISSUE TITLE
POLFREE binding not generated (kernel/sync/condvar.rs)

### ISSUE THREAD

**Issue by kdave** [Rust-for-Linux/linux#797]
I've noticed there's an extra definition of `POLLFREE` in file rust/kernel/sync/condvar.rs. The C macro definition is in include/uapi/asm-generic/poll.h

```
#define POLLFREE     (__force __poll_t)0x4000
```

Other defines do not have the typecast and the macros appear in the generated bindings (POLLIN, etc). The problem is the type cast, changing that to eg. to `unsigned long` also does not generate it so it's probably a bug in `bindgen`.

**Comment by ojeda** [comment]
Yeah, `bindgen` only works for trivial macros (it has some support for evaluating expressions like `#define A 1+1`, though).

For anything that it does not handle, we manually write an equivalent.

**Comment by ojeda** [comment]
I will close this by cleaning up the `TODO` comment since it is known.

**Comment by ojeda** [comment]
Closing, since it applied to the old `rust` branch.
