### ISSUE TITLE
scripts/Makefile.modfinal BTF change necessary, even though config RUST depends on !DEBUG_INFO_BTF?

### ISSUE THREAD

**Issue by nickdesaulniers** [Rust-for-Linux/linux#871]
scripts/Makefile.modfinal modifications in v9 are related to btf generation of modules. I'm curious if that change is necessary, since config RUST as defined in init/Kconfig depends on !DEBUG_INFO_BTF?

**Comment by YakoYakoYokuYoku** [comment]
Please see #735 and #872.

**Comment by ojeda** [comment]
Closing, since those other two issues were addressed -- if there is something that still needs to be addressed, please let us know!
