### ISSUE TITLE
Feature request: declaring float constants (float_bits_conv / const_float_bits_conv)

### ISSUE THREAD

**Issue by hoshinolina** [Rust-for-Linux/linux#878]
I need to define a large number of float constants as part of structures that are shared with hardware/firmware. Floats aren't allowed in the kernel, but the kernel doesn't really have to do math with these, it just needs to initialize them.

Right now I'm doing this:

```rust
#[derive(Default, Debug, Copy, Clone)]
pub(crate) struct F32(u32);

impl F32 {
    pub(crate) const fn new(v: f32) -> F32 {
        F32(v.to_bits())
    }
}

[...]

T {
    foo: F32::new(0.123),
    bar: F32::new(0.456),
}
```

But that needs the `float_bits_conv` / `const_float_bits_conv` features. Is there any chance of enabling those in the kernel?

Alternatively, this could be a simple proc macro... (or maybe even a very ugly macro or function that parses it as a string in const context, or similar, using only integer math?). Thoughts?

**Comment by hoshinolina** [comment]
I'm now using a macro on top of the above code to enforce the const context, but I still need `const_float_bits_conv` for this...

```rust
#[macro_export]
macro_rules! const_f32 {
    ($val:expr) => {{
        const _K: F32 = F32::new($val);
        _K
    }};
}
```

**Comment by nbdd0121** [comment]
You can use inline const block for instead of using macros but that requires an unstable feature as well.

**Comment by nbdd0121** [comment]
I think transmute + the macro should do the trick now without using unstable features?

**Comment by hoshinolina** [comment]
Ah, transmute is const! I didn't know that. Indeed, that works fine, and with the macro it can be made safe enough, so we can close this! Thank you!
