### ISSUE TITLE
openssl-dev in CI container (for certs/extract-cert)

### ISSUE THREAD

**Issue by hoshinolina** [Rust-for-Linux/linux#892]
`openssl-dev` (or equivalent) is necessary to build `certs/extract-cert` in the kernel. This can end up a dependency if `CONFIG_SYSTEM_TRUSTED_KEYRING` is set, which gets pulled in by default if wireless support is built in (due to the regulatory DB stuff). It can be worked around with `CONFIG_EXPERT` and `CONFIG_CFG80211_CERTIFICATION_ONUS`, which is what I'm doing now, but it would be nice if the package was added to the build container so these configs can be built without workarounds (I'd like to have our CI test the same config, or as close as possible, to the one we ship to users).

```  HOSTCC  certs/extract-cert
certs/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory
   21 | #include <openssl/bio.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.host:111: certs/extract-cert] Error 1```

**Comment by ojeda** [comment]
> it would be nice if the package was added to the build container

Of course -- will do! :)
