### ISSUE TITLE
Change `unwrap()`s to `expect()`s in `module.rs`

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#90]
Although we don't get output unless we use `-Z proc-macro-backtrace`, it is a good idea to provide some more details like we do for some of the others, e.g. in:

    fn expect_punct(it: &mut token_stream::IntoIter) -> char {
        if let TokenTree::Punct(punct) = it.next().unwrap() {
        ...

This `unwrap()` may fail if we find the end of the stream unexpectedly (because the user didn't pass the arguments that we expected).

**Comment by Sylfrena** [comment]
Hullo,
Can I work on this issue?

**Comment by ojeda** [comment]
Of course!

**Comment by Sylfrena** [comment]
@ojeda Hi, this is something that should be obvious to me, but i am not really sure how to compile the changes I make. Rustc gives me [these](https://paste.ubuntu.com/p/cQKY82yjP8/) errors (which  are not related to the changes I made). And using 
`make CC=clang M=rust` is not really catching errors (I tried introducing some). 
Running make for the entire kernel is sort of time taking, but is that the only way, or I am I missing something here?

**Comment by ojeda** [comment]
No worries! In general, the mailing list is best for things like this.

> Running make for the entire kernel is sort of time taking, but is that the only way, or I am I missing something here?

Running `make CC=clang` for the entire kernel should only recompile what is needed -- even with a single core it should be very quick (handful of seconds) to reach the point where it compiles the Rust code if everything else is already compiled. Are you perhaps cleaning the build every time? Avoid using `M=`, it shouldn't be needed for your use case.
