### ISSUE TITLE
Makefile.package TAR_CONTENT need to add rust

### ISSUE THREAD

**Issue by paranlee** [Rust-for-Linux/linux#928]
When build with `make rpm-pkg` , rpm build fail because tarball have not contains `rust/` directory contents.
We need to add `rust` argument at **TAR_CONTENT** in `scripts/Makefile.package` script.

**Comment by ojeda** [comment]
In mainline at https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=df1f1ea9569eef05c006aeae1d65fbf6c2339677.
