### ISSUE TITLE
objtool warnings in KernelCI report

### ISSUE THREAD

**Issue by nathanchance** [Rust-for-Linux/linux#945]
Apologies if this has been reported already! KernelCI recently started testing with Rust and it seems that there are quite a few `objtool` warnings for Rust code: https://lore.kernel.org/llvm/639aba22.170a0220.d9ab4.4ff4@mx.google.com/

**Comment by ojeda** [comment]
Thanks for the report as usual! We briefly discussed it on a meeting on Wednesday.

IBT/Retpoline/Rethunk require a few things to be in place:

  - Passing `-Zcf-protection=branch` together with a new flag `-Zno-jump-tables` to mimic GCC/Clang's which `rustc` currently does not have. I have submitted a PR: https://github.com/rust-lang/rust/pull/105812.

  - New flags `-Zfunction-return=thunk-extern` to be implemented and so on.

In a patched `rustc` 1.66.0 with `-Zno-jump-tables` and a hacky `-Zfunction-return=thunk-extern` + an upgraded-to-Rust-1.66.0 kernel, the only warning remaining in defconfig I have is:

```
vmlinux.o: warning: objtool: rust_begin_unwind+0x70: unreachable instruction
```

The resulting kernel boots in QEMU, but will need to be tested properly in real hardware.

We will have to wait at least a couple months to get all the pieces in place, so I have submitted a PR to our KernelCI config to disable these: https://github.com/kernelci/kernelci-core/pull/1580

**Comment by ojeda** [comment]
For reference, a couple updates:

  - https://lore.kernel.org/rust-for-linux/20231009224347.2076221-1-mmaurer@google.com/
  - https://lore.kernel.org/rust-for-linux/20231023174449.251550-1-ojeda@kernel.org/

**Comment by ojeda** [comment]
The series https://lore.kernel.org/rust-for-linux/20240725183325.122827-1-ojeda@kernel.org/ should fix all of those warnings.

**Comment by ojeda** [comment]
Applied to `rust-next` -- if anyone notices new warnings, please let us know. Thanks!
