### ISSUE TITLE
No errors are shown in the VSCode "problems" tab

### ISSUE THREAD

**Issue by dwlsalmeida** [Rust-for-Linux/linux#951]
Hi all, 

First off, I was going to send this to the rust-for-linux mailing list, but I see that it is mainly used for patches, so in the interest of not polluting it I've decided to open an issue here instead.

Here's for the actual issue: no errors are shown in the VSCode "problems" tab here, even after setting the path to rust-project.json in "rust-analyzer.linkedProjects".

This is slightly incovenient because it means that no errors are shown in the UI while writing Rust code.

Some brief research [0] indicates that this is to be expected, i.e.:

> 
> 
> Note that calls to cargo check are disabled when using
> rust-project.json by default, so compilation errors and warnings will
> no longer be sent to your LSP client. To enable these compilation
> errors you will need to specify explicitly what command rust-analyzer
> should run to perform the checks using the
> checkOnSave.overrideCommand configuration. As an example, the
> following configuration explicitly sets cargo check as the
> checkOnSave command.
> 
> 1
> 
> 	
> 
> { "rust-analyzer.checkOnSave.overrideCommand": ["cargo", "check",
> "--message-format=json"] }
> 
> The checkOnSave.overrideCommand requires the command specified to
> output json error messages for rust-analyzer to consume. The
> --message-format=json flag does this for cargo check so whichever
> command you use must also output errors in this format. See the
> Configuration section for more information.
> 

I expect that there is no infrastructure in place to output the errors in JSON format.

This brings me to the topic of problem matchers. Are they - in conjunction with a separate build task - the recommended way to get the errors to show? If so, is there a problem matcher in use by all of the community?

Lastly, can I get an invite to the Zulip chat, please?

-- Daniel

[0] https://rust-analyzer.github.io/manual.html#non-cargo-based-projects

**Comment by bjorn3** [comment]
You can create a vscode task to run `make`. I think you an set the `problemMatcher` for this task to the literal string `$rustc` to make the results appear inline with the source code.

**Comment by dwlsalmeida** [comment]
thanks @bjorn3 I was trying to make sure the problem matcher approach was the right thing to do

I will try that!

**Comment by ojeda** [comment]
> Lastly, can I get an invite to the Zulip chat, please?

I think nowadays the "Sign up" button should work when you try to access it -- but I am happy to send it too (to the email in your profile?).

**Comment by dwlsalmeida** [comment]
@ojeda Could you please send to daniel.almeida@collabora.com if you have the time? :)

**Comment by ojeda** [comment]
Done -- welcome! (Did you have a problem with that "Sign up" page? I am asking in case others may have too)

**Comment by dwlsalmeida** [comment]
To be honest, I was under the impression that you could only log in through Google/Github/Gitlab. I just saw that you can register using a regular email too, which I just confirmed as working as well.

Thanks, all is working fine! :)

**Comment by ojeda** [comment]
Ah, makes sense. Thanks for letting me know! Yeah, I think the option is a bit hidden... Would a small note in the `README.md` help?

**Comment by ojeda** [comment]
I think we can close this (?).

We also discussed how well rust-analyzer was working in Kangrejos 2024.

**Comment by dwlsalmeida** [comment]
I did not test this yet, but , as explained in the Zulip thread, there appears to be a way that is also employed by other projects like rustc. I am ok with closing this.
