### ISSUE TITLE
add `rust-toolchain.toml`

### ISSUE THREAD

**Issue by TheAlgorythm** [Rust-for-Linux/linux#953]
I'm not sure if it works with this setup, but it should make the setup process easier.
The setup of [`Documentation/rust/quick-start.rst`](https://github.com/Rust-for-Linux/linux/blob/rust/Documentation/rust/quick-start.rst#rustc) includes the following commands:
```console
rustup override set $(scripts/min-tool-version.sh rustc)
rustup component add rust-src
```

An equivalent `rust-toolchain.toml` should be:

```toml
[toolchain]
channel = "1.66.0"
components = [ "rust-src" ]
```

This should setup the environment automatically and therefore reduce the steps for building the kernel.
The documentation for this can be found [here](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)

(I am not a kernel developer (yet) and therefore don't know if it works with its infrastructure)

**Comment by ojeda** [comment]
The directory override will take priority over that file, so users giving an override (in the root folder) would still be able to use their own toolchain, right? e.g. @nbdd0121 often uses a newer toolchain, IIRC.

**Comment by bjorn3** [comment]
Indeed. `rust-toolchain.toml` is the last thing checked before falling back to the global default. Directory overrides happen before that. See https://rust-lang.github.io/rustup/overrides.html

**Comment by ojeda** [comment]
Thanks @bjorn3! I wanted to make sure I read the docs correctly. In that case, I think we can do this.

Would you like to submit the patch @TheAlgorythm or do you prefer somebody else does it (with e.g. a `Suggested-by` from you)?

If you want to send it yourself, please see https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin for details (the kernel requires using the real name and signing your work under the DCO).

I will mark this as a good first issue too.

**Comment by nbdd0121** [comment]
I wanted to do this earlier, but then it feels ugly having to name it `rust-toolchain.toml` and place it in the git root directory. I would probably send the patch long while ago if the file could be named `.rust-toolchain.toml`.

**Comment by ojeda** [comment]
Ah, yeah, if it does not allow to be hidden, that is indeed quite painful. Then we should request that to `rustup` first.

**Comment by ojeda** [comment]
Done! https://github.com/rust-lang/rustup/issues/3182

**Comment by TheAlgorythm** [comment]
> Would you like to submit the patch @TheAlgorythm or do you prefer somebody else does it?

I can do that, but probably we should wait for `rustup` to add the support as I can understand, that such file shouldn't clutter the root. If they will change it I can create a PR.
In the meantime I will try if it's possible to place the file in another directory than the root.

**Comment by ojeda** [comment]
For reference, @aliceinwire sent a PR about this before you answered but after I asked you https://github.com/Rust-for-Linux/linux/pull/954. Maybe you could please talk to each other about how to handle this when the time comes to send it upstream :)

**Comment by TheAlgorythm** [comment]
Ah ok. I haven't seen the PR before. I'm fine with it :)

**Comment by TheAlgorythm** [comment]
I've created a [PR](https://github.com/rust-lang/rustup/pull/3195) at rustup. But is this the normal procedure?

**Comment by ojeda** [comment]
Thanks! Referenced it at https://github.com/Rust-for-Linux/linux/issues/396.

> But is this the normal procedure?

What do you mean?

**Comment by TheAlgorythm** [comment]
> What do you mean?

Is there a RFC or something else needed? Or is it enough when the maintainers like it.

**Comment by ojeda** [comment]
https://github.com/rust-lang/rustup/blob/master/CONTRIBUTING.md does not seem to refer to it, though I do see a couple mentions of "RFCs" for rustup from a quick search. I guess they will let you know in the PR if that is the case.

**Comment by ojeda** [comment]
The Rust version is not pinned anymore, so I think at this point we don't need this, right?
