### ISSUE TITLE
Sort documentation's arch support table properly

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#965]
https://lore.kernel.org/rust-for-linux/CANiq72nXMsnUsJNZOG-QZiCVOqa9dRUSMc4RAS3ExLZNJ7VhHg@mail.gmail.com/

This issue is about the table that will appear in 6.3-rc1 (you can also find it in the UML `next` branch), but not the `rust` branch here.

It requires testing with `htmldocs` to see if there are any new diagnostics, as well as double-checking the generated result.

Please send the patch directly to the mailing lists (UML & Rust), and recall to add "Link: " and "Reported-by: " tags to the original report and that the kernel requires signing the commit under the DCO.

**Comment by ThomasBamelis** [comment]
I mailed a patch for this
[PATCH] rust: sort uml documentation arch support table

**Comment by ojeda** [comment]
Could you please link it in lore.kernel.org? I haven't received it, ~and I don't see it in lore either.~ I guess vger has a delay (next time, please Cc maintainers directly too, you can use `scripts/get_maintainers.pl` to get the list).

**Comment by ojeda** [comment]
Ah, this one: https://lore.kernel.org/rust-for-linux/I0YeaNjTtc4Nh47ZLJfAs6rgfAc_QZxhynNfz-GQKssVZ1S2UI_cTScCkp9-oX-hPYVcP3EfF7N0HMB9iAlm1FcvOJagnQoLeHtiW3bGCgM=@bamelis.dev/

**Comment by ThomasBamelis** [comment]
Thank you very much for that tip!
This was my first ever open-source patch, sorry for any submission mistakes, highly appreciate the tips

**Comment by ojeda** [comment]
Thanks to you for sending it! The patch looks fine, nice work! There are a couple trivial nits that I may mention in the mailing list, but nothing important.

**Comment by ojeda** [comment]
Landed in mainline.
