### ISSUE TITLE
Consider generating docs for `core` and `alloc` too

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#97]
Currently the generated intra-doc links go to the official Rust docs webpage.

Consider generating `core` and `alloc` so that:
  - It doesn't require internet (for local builds).
  - It doesn't depend on another host (for kernel.org builds).
  - They are consistent with the compiled crates (e.g. nightly Rust could have added features not present in the local version).

**Comment by ojeda** [comment]
It turns out that if generate `core` and `alloc` for offline support, some links inside those two crates break:
  - Links to `std`: because they assume `std` is generated locally (i.e. with a relative path). Using `--extern-html-root-url` doesn't seem to work, likely because they are explicit links rather than intra-links.
  - Links to reference/nomicon/etc.: similar, except those could never be intra-links.

A potential solution is fixing the links "on the fly", but we would need to see how easy/reliable that would be.

For the moment, I think it is best to keep things working vs. supporting offline browsing. There are several reasons:
  - Kernel developers new to Rust may just think things in the Rust standard library are broken (rightfully so), and may have never read the docs in the official webpage, which means they will spend time finding out where the information is and/or reporting the issue.
  - Since the plan is to have the docs on kernel.org, people will likely get accustomed to read them there vs. generating them locally, which means they are already relying on being online.
  - It is easier to maintain. If we successfully get into mainline, we can revisit to see whether it is worth doing something else.

Thanks to @wusyong for #129 which helped identifying these problems.

**Comment by frazar** [comment]
It seems like the docs generation is already working for both crates on the `rust-next` branch:

<img src="https://github.com/user-attachments/assets/136638c3-3606-4441-91aa-fc023e8b9f54" width="500"/>

For the sake of tracing, I think this was enabled

- on the `rust` branch by
  - by 38a10b4f9d0e80d4114d41e88265852967793559 for `alloc`
  - by afc3acf31bb75898cbbc30fa0738aff37548f9a5 for `core`
  
- on the `rust-next` branch by 2f7ab1267dc9b2d1f29695aff3211c87483480f3

So maybe now this issue can be closed?

**Comment by ojeda** [comment]
Yeah, this is a stale issue -- thanks!
