### ISSUE TITLE
rust: str: "requierments" typo

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#978]
There is a typo in `str.rs`: "requierments".

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to use a proper title for the commit (`rust: str: fix .......`), to sign your commit under the Developer's Certificate of Origin, to add a `Fixes: ` tag to the original commit, a `Reported-by: ` tag and a `Link: ` tag to this report.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel.

**Comment by pblass** [comment]
I would like to take this as my first kernel contribution.

**Comment by ojeda** [comment]
Of course, go ahead! :)

**Comment by ojeda** [comment]
https://lore.kernel.org/rust-for-linux/20230303-str-rs-typo-v1-1-d022b4a57591@mailbox.org/

**Comment by onur-ozkan** [comment]
seems this is resolved with https://github.com/Rust-for-Linux/linux/commit/88e8c2ec4ab84f9f05ed5af9693a3972baf386c4

**Comment by ojeda** [comment]
Yeah, this one is landing in mainline soon (via `rust-fixes`).

**Comment by ojeda** [comment]
Landed in mainline.
