### ISSUE TITLE
How to configure rust (standard library) source

### ISSUE THREAD

**Issue by ghost** [Rust-for-Linux/linux#98]
https://github.com/Rust-for-Linux/linux/blob/304ee695107a8b49a833bb1f02d58c1029e43623/rust/Makefile#L119

There are multiple issues I see here:

- It should be possible for the user to configure the rust source directory independently of the rust sysroot
- Currently only sources from the `library/` subdirectory are used. If it stays like this in the forseeable future, I would like to change the `rustc_src` variable to a `rust_lib_src` variable, which points directly to the `library/` subdirectory. For example my distribution has an own package `rustLibSrc`, which will decrease the amount of downloads needed.

**Comment by bjorn3** [comment]
> Currently only sources from the library/ subdirectory are used.

This may change as the layout of the rust repo changes. For example libcore used to be in the `src/libcore` dir of the rust repo and could thus be found in `$rustc_src/src/libcore`. A while ago it was changed to be in the `library/core` dir. It is possible that this will change again in the future, though I don't think it is likely to happen in the forseeable future.

**Comment by kloenk** [comment]
Fixed in #226
